/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PinballMVP.glb -T -o src/components/models/PinballMVP.tsx 
Files: public/models/PinballMVP.glb [728.59MB] > /Users/adrienallard/Développement/HETIC/Pinball_ThreeJs/frontend/src/components/models/PinballMVP-transformed.glb [23.95MB] (97%)
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { SkeletonUtils } from "three-stdlib";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    visual_ground_2: THREE.Mesh;
    visual_bg_sunset_2: THREE.Mesh;
    visual_env_pyramid: THREE.Mesh;
    visual_env_sand: THREE.Mesh;
    visual_crane: THREE.Mesh;
    visual_env_ruin_left_1: THREE.Mesh;
    visual_env_ruin_right_0: THREE.Mesh;
    env_ruins1_LOD0: THREE.Mesh;
    env_ruins1_LOD0_1: THREE.Mesh;
    oasis_vegetation_back_LOD0: THREE.Mesh;
    oasis_vegetation_back_LOD0_1: THREE.Mesh;
    mummy_button_LOD0: THREE.Mesh;
    mummy_button_LOD0_1: THREE.Mesh;
    visual_oasis_lake_2: THREE.Mesh;
    visual_env_tools: THREE.Mesh;
    visual_nile_vegetables: THREE.Mesh;
    visual_sarcophagus01_basex: THREE.Mesh;
    visual_nile: THREE.Mesh;
    visual_habit_right_9: THREE.Mesh;
    visual_scarab_flasher_01_16: THREE.Mesh;
    visual_scarab_flasher_plane_01_17: THREE.Mesh;
    visual_mpf_metal_wires_11: THREE.Mesh;
    visual_sphinx_1: THREE.Mesh;
    visual_mummy_floor: THREE.Mesh;
    visual_lg_10x: THREE.Mesh;
    visual_locker: THREE.Mesh;
    visual_ramp_back: THREE.Mesh;
    visual_miniplayfield: THREE.Mesh;
    visual_obj_flipper_mini_left: THREE.Mesh;
    visual_obj_flipper_mini_left001: THREE.Mesh;
    visual_obj_flipper_mini_right: THREE.Mesh;
    visual_obj_flipper_mini_right001: THREE.Mesh;
    visual_droptarget_mpf_01_gfx: THREE.Mesh;
    visual_shadow_flipper_mini_right: THREE.Mesh;
    visual_ramp_right_sand: THREE.Mesh;
    visual_middle_stuff_top: THREE.Mesh;
    visual_bridge_part_01: THREE.Mesh;
    visual_obj_target_7: THREE.Mesh;
    visual_obj_target001_6: THREE.Mesh;
    visual_spindisk_mpf: THREE.Mesh;
    visual_obj_flipper_left_bottom: THREE.Mesh;
    visual_obj_flipper_right_bottom: THREE.Mesh;
    visual_pyramid: THREE.Mesh;
    visual_obj_spinner_11: THREE.Mesh;
    visual_lg_gi_lamps_4: THREE.Mesh;
    visual_slingshot_flash_obj_left: THREE.Mesh;
    holes_nocoll_LOD0: THREE.Mesh;
    holes_nocoll_LOD0_1: THREE.Mesh;
    waterlvl_LOD0: THREE.Mesh;
    waterlvl_LOD0_1: THREE.Mesh;
    visual_playfield: THREE.Mesh;
    visual_under_pf: THREE.Mesh;
    visual_anu_card_01_gfx: THREE.Mesh;
    visual_lg_army_of_anubis_02: THREE.Mesh;
    coll_ramp_back001: THREE.Mesh;
    visual_anubis: THREE.SkinnedMesh;
    visual_ornate_torch_04_20: THREE.SkinnedMesh;
    coll_locker_door_2001: THREE.SkinnedMesh;
    visual_locker_door_2: THREE.SkinnedMesh;
    visual_sarcophagus01_door_3001: THREE.SkinnedMesh;
    visual_anubis_under_pf_11001: THREE.SkinnedMesh;
    visual_scarabeus: THREE.SkinnedMesh;
    visual_anubis_under_pf2001: THREE.SkinnedMesh;
    visual_torch_left_24001: THREE.SkinnedMesh;
    visual_torch_right_28001: THREE.SkinnedMesh;
    visual_ornate_torch_01_14001: THREE.SkinnedMesh;
    visual_ornate_torch_03_17: THREE.SkinnedMesh;
    visual_crochead1001: THREE.SkinnedMesh;
    visual_crochead2_19001: THREE.SkinnedMesh;
    visual_crochead3001: THREE.SkinnedMesh;
    visual_crochead4_18001: THREE.SkinnedMesh;
    visual_waterlvl_bubble_2001: THREE.SkinnedMesh;
    visual_crocodile_plunger: THREE.SkinnedMesh;
    mummy_LOD0: THREE.SkinnedMesh;
    mummy_LOD0_1: THREE.SkinnedMesh;
    mummy_LOD0_2: THREE.SkinnedMesh;
    visual_slingshot_left_10001: THREE.SkinnedMesh;
    visual_slingshot_right_7001: THREE.SkinnedMesh;
    root_crocodile: THREE.Bone;
    anubis_root: THREE.Bone;
    mummy_root: THREE.Bone;
    Root_Torches: THREE.Bone;
    locker_root: THREE.Bone;
    sarcophagus01_root: THREE.Bone;
    anubis_undpf_root: THREE.Bone;
    scarabeus_root: THREE.Bone;
    anubis_undpf_root_1: THREE.Bone;
    Root_Torches_1: THREE.Bone;
    Root_Torches_2: THREE.Bone;
    Root_Torches_3: THREE.Bone;
    Root_Torches_4: THREE.Bone;
    crochead_root: THREE.Bone;
    crochead_root_1: THREE.Bone;
    crochead_root_2: THREE.Bone;
    crochead_root_3: THREE.Bone;
    root_left_sling: THREE.Bone;
    root_right_sling: THREE.Bone;
    waterlevel_group: THREE.Bone;
  };
  materials: {
    M_sand_tile: THREE.MeshStandardMaterial;
    M_bg_sunset: THREE.MeshStandardMaterial;
    M_env_pyramid: THREE.MeshStandardMaterial;
    M_bg_env_ground: THREE.MeshStandardMaterial;
    M_crane: THREE.MeshStandardMaterial;
    M_overlap: THREE.MeshStandardMaterial;
    M_ruin_right: THREE.MeshStandardMaterial;
    M_env_ruins1: THREE.MeshStandardMaterial;
    M_broken_stone1: THREE.MeshStandardMaterial;
    M_palm_bark: THREE.MeshStandardMaterial;
    M_vegetation: THREE.MeshStandardMaterial;
    M_mummy_button: THREE.MeshStandardMaterial;
    M_mummy_button_alpha: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    M_env_tools: THREE.MeshStandardMaterial;
    M_vegetation_02: THREE.MeshStandardMaterial;
    M_nile_ramp: THREE.MeshStandardMaterial;
    scarab_flasher: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    M_sphinx: THREE.MeshStandardMaterial;
    m_mummy_path: THREE.MeshStandardMaterial;
    lamp_playfield: THREE.MeshStandardMaterial;
    M_ramp_back: THREE.MeshStandardMaterial;
    M_miniplayfield: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_left: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_left2: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_right: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_right2: THREE.MeshStandardMaterial;
    M_midlestuff: THREE.MeshStandardMaterial;
    flipper_arms_shadow: THREE.MeshStandardMaterial;
    M_ramps: THREE.MeshStandardMaterial;
    M_bridge: THREE.MeshStandardMaterial;
    target: THREE.MeshStandardMaterial;
    ["metal_sidewalls.001"]: THREE.MeshStandardMaterial;
    M_spindisk: THREE.MeshStandardMaterial;
    M_flipper_arm_left: THREE.MeshStandardMaterial;
    M_flipper_arm_right: THREE.MeshStandardMaterial;
    M_pyramid__Inst: THREE.MeshStandardMaterial;
    M_spinner: THREE.MeshStandardMaterial;
    lamp_playfield_white: THREE.MeshStandardMaterial;
    M_slingshot_flasher_obj: THREE.MeshStandardMaterial;
    ["M_playfield_cutout.001"]: THREE.MeshStandardMaterial;
    M_black: THREE.MeshStandardMaterial;
    gold: THREE.MeshStandardMaterial;
    waterlvl: THREE.MeshStandardMaterial;
    playfield: THREE.MeshStandardMaterial;
    M_underplayfield: THREE.MeshStandardMaterial;
    M_army_of_anubis: THREE.MeshStandardMaterial;
    M_anubis_head_eyes: THREE.MeshStandardMaterial;
    M_anubis_head: THREE.MeshStandardMaterial;
    M_Torches: THREE.MeshStandardMaterial;
    M_locker: THREE.MeshStandardMaterial;
    M_sarcophagus: THREE.MeshStandardMaterial;
    M_scarabeus: THREE.MeshStandardMaterial;
    M_crocodile_plunger: THREE.MeshStandardMaterial;
    water_level_bubble: THREE.MeshStandardMaterial;
    M_mummy: THREE.MeshStandardMaterial;
    M_mummy_eye: THREE.MeshStandardMaterial;
    M_mummy_jewel: THREE.MeshStandardMaterial;
    rubber: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export default function PinballMVP(props: JSX.IntrinsicElements["group"]) {
  const { scene } = useGLTF("/models/PinballMVP-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  // console.log(Object.keys(nodes));
  // console.log(nodes.visual_obj_flipper_mini_right.geometry);
  // React.useEffect(() => {
  //   clone.traverse((child) => {
  //     console.log(child.type, child.name);
  //   });
  // }, [clone]);
  clone.traverse((obj) => {
    if (obj.name.includes("coll")) {
      console.log("FOUND COLL:", obj);
    }
  });
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.root_crocodile} />
      <primitive object={nodes.anubis_root} />
      <primitive object={nodes.mummy_root} />
      <primitive object={nodes.Root_Torches} />
      <primitive object={nodes.locker_root} />
      <primitive object={nodes.sarcophagus01_root} />
      <primitive object={nodes.anubis_undpf_root} />
      <primitive object={nodes.scarabeus_root} />
      <primitive object={nodes.anubis_undpf_root_1} />
      <primitive object={nodes.Root_Torches_1} />
      <primitive object={nodes.Root_Torches_2} />
      <primitive object={nodes.Root_Torches_3} />
      <primitive object={nodes.Root_Torches_4} />
      <primitive object={nodes.crochead_root} />
      <primitive object={nodes.crochead_root_1} />
      <primitive object={nodes.crochead_root_2} />
      <primitive object={nodes.crochead_root_3} />
      <primitive object={nodes.root_left_sling} />
      <primitive object={nodes.root_right_sling} />
      <primitive object={nodes.waterlevel_group} />
      <mesh
        geometry={nodes.visual_ground_2.geometry}
        material={materials.M_sand_tile}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bg_sunset_2.geometry}
        material={materials.M_bg_sunset}
        position={[-1.212, 7.019, -181.084]}
        scale={[116.878, 86.342, 116.878]}
      />
      <mesh
        geometry={nodes.visual_env_pyramid.geometry}
        material={materials.M_env_pyramid}
        position={[-98.587, 23.747, -79.016]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_sand.geometry}
        material={materials.M_bg_env_ground}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_crane.geometry}
        material={materials.M_crane}
        position={[54.899, 7.531, 42.026]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_ruin_left_1.geometry}
        material={materials.M_overlap}
        position={[-35.975, 4.047, 33.058]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_ruin_right_0.geometry}
        material={materials.M_ruin_right}
        position={[49.166, 2.842, -1.616]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.env_ruins1_LOD0.geometry}
          material={materials.M_env_ruins1}
        />
        <mesh
          geometry={nodes.env_ruins1_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0.geometry}
          material={materials.M_palm_bark}
        />
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0_1.geometry}
          material={materials.M_vegetation}
        />
      </group>
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.mummy_button_LOD0.geometry}
          material={materials.M_mummy_button}
        />
        <mesh
          geometry={nodes.mummy_button_LOD0_1.geometry}
          material={materials.M_mummy_button_alpha}
        />
      </group>
      <mesh
        geometry={nodes.visual_oasis_lake_2.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_tools.geometry}
        material={materials.M_env_tools}
        position={[-14.75, -2.125, 58.467]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_nile_vegetables.geometry}
        material={materials.M_vegetation_02}
        position={[4.471, 3.698, -26.384]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_sarcophagus01_basex.geometry}
        material={materials.M_sarcophagus}
        position={[26.613, 4.618, -3.19]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_nile.geometry}
        material={materials.M_nile_ramp}
        position={[4.471, 3.698, -26.384]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_habit_right_9.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.237, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_01_16.geometry}
        material={materials.scarab_flasher}
        position={[-25.043, 3.413, 11.054]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_01_17.geometry}
        material={materials.PaletteMaterial002}
        position={[-25.14, 3.73, 11.062]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_mpf_metal_wires_11.geometry}
        material={materials.rubber}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_sphinx_1.geometry}
        material={materials.M_sphinx}
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_mummy_floor.geometry}
        material={materials.m_mummy_path}
        position={[23.048, -2.621, 35.828]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_10x.geometry}
        material={materials.lamp_playfield}
        position={[18.346, -2.282, 50.746]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_locker.geometry}
        material={materials.M_locker}
        position={[13.234, 11.209, -35.046]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_ramp_back.geometry}
        material={materials.M_ramp_back}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_miniplayfield.geometry}
        material={materials.M_miniplayfield}
        position={[-2.49, 6.799, -32.435]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_mini_left.geometry}
        material={materials.M_flipper_mini_arm_left}
        position={[-17.148, 6.82, -22.066]}
        rotation={[0, -0.855, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_mini_left001.geometry}
        material={materials.M_flipper_mini_arm_left2}
        position={[11.295, 6.82, -22.523]}
        rotation={[0, -1.012, 0]}
        scale={94.51}
      />
      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_mini_right.geometry} */}
      {/*   material={materials.M_flipper_mini_arm_right} */}
      {/*   position={[-1.759, 6.82, -22.973]} */}
      {/*   rotation={[0, 0.96, Math.PI]} */}
      {/*   scale={94.51} */}
      {/* /> */}
      <mesh
        geometry={nodes.visual_obj_flipper_mini_right001.geometry}
        material={materials.M_flipper_mini_arm_right2}
        position={[23.193, 6.82, -19.859]}
        rotation={[0, 0.367, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_01_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-17.016, 6.277, -28.049]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[94.51, 94.51, 74.916]}
      />
      <mesh
        geometry={nodes.visual_shadow_flipper_mini_right.geometry}
        material={materials.flipper_arms_shadow}
        position={[-2.849, 6.839, -21.243]}
        rotation={[0, 0.96, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_ramp_right_sand.geometry}
        material={materials.M_ramps}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_middle_stuff_top.geometry}
        material={materials.rubber}
        position={[-3.899, -2.357, -3.675]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bridge_part_01.geometry}
        material={materials.M_bridge}
        position={[-0.049, 6.744, -28.022]}
        rotation={[0, 0.122, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_target_7.geometry}
        material={materials.target}
        position={[19.009, 6.813, -30.501]}
        rotation={[3.141, -1.32, 3.141]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_target001_6.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[23.593, 6.813, -25.943]}
        rotation={[3.142, -0.465, 3.142]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_spindisk_mpf.geometry}
        material={materials.M_spindisk}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_left_bottom.geometry}
        material={materials.M_flipper_arm_left}
        position={[-9.887, -5.158, 52.106]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_right_bottom.geometry}
        material={materials.M_flipper_arm_right}
        position={[5.495, -5.158, 52.106]}
        rotation={[0, Math.PI / 6, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_pyramid.geometry}
        material={materials.M_pyramid__Inst}
        position={[-8.531, -5.158, -13.208]}
        rotation={[0, 0.175, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_spinner_11.geometry}
        material={materials.M_spinner}
        position={[-22.382, -1.98, -3.51]}
        rotation={[Math.PI / 2, 0, 2.827]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_gi_lamps_4.geometry}
        material={materials.lamp_playfield_white}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_slingshot_flash_obj_left.geometry}
        material={materials.M_slingshot_flasher_obj}
        position={[-14.642, -1.733, 35.718]}
        scale={94.51}
      />
      {/* <group position={[-1.953, -12.649, 20.335]} scale={94.51}> */}
      {/*   <mesh */}
      {/*     geometry={nodes.holes_nocoll_LOD0.geometry} */}
      {/*     material={materials["M_playfield_cutout.001"]} */}
      {/*   /> */}
      {/*   <mesh */}
      {/*     geometry={nodes.holes_nocoll_LOD0_1.geometry} */}
      {/*     material={materials.M_black} */}
      {/*   /> */}
      {/* </group> */}
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.waterlvl_LOD0.geometry}
          material={materials.gold}
        />
        <mesh
          geometry={nodes.waterlvl_LOD0_1.geometry}
          material={materials.waterlvl}
        />
      </group>
      <mesh
        geometry={nodes.visual_playfield.geometry}
        material={materials.playfield}
        position={[-1.212, -5.158, 15.409]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_under_pf.geometry}
        material={materials.M_underplayfield}
        position={[-2.199, -7.379, 25.546]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_anu_card_01_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[14.648, -8.517, 14.462]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_army_of_anubis_02.geometry}
        material={materials.M_anubis_head_eyes}
        position={[13.512, -5.158, -0.808]}
        rotation={[0, 1.286, -Math.PI / 2]}
        scale={94.51}
      />
      {/* <mesh */}
      {/*   geometry={nodes.coll_ramp_back001.geometry} */}
      {/*   material={nodes.coll_ramp_back001.material} */}
      {/*   position={[-1.212, -5.158, 10.211]} */}
      {/*   scale={94.51} */}
      {/* /> */}
      <skinnedMesh
        geometry={nodes.visual_anubis.geometry}
        material={materials.M_anubis_head}
        skeleton={nodes.visual_anubis.skeleton}
        position={[13.512, -5.158, -0.808]}
        rotation={[0, -0.373, 0]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_ornate_torch_04_20.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_ornate_torch_04_20.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      {/* <skinnedMesh */}
      {/*   geometry={nodes.coll_locker_door_2001.geometry} */}
      {/*   material={nodes.coll_locker_door_2001.material} */}
      {/*   skeleton={nodes.coll_locker_door_2001.skeleton} */}
      {/*   position={[-1.212, -5.158, 10.211]} */}
      {/*   scale={94.51} */}
      {/* /> */}
      {/* <skinnedMesh */}
      {/*   geometry={nodes.visual_locker_door_2.geometry} */}
      {/*   material={materials.M_locker} */}
      {/*   skeleton={nodes.visual_locker_door_2.skeleton} */}
      {/*   position={[-1.212, -5.158, 10.211]} */}
      {/*   scale={94.51} */}
      {/* /> */}
      <skinnedMesh
        geometry={nodes.visual_sarcophagus01_door_3001.geometry}
        material={materials.M_sarcophagus}
        skeleton={nodes.visual_sarcophagus01_door_3001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_anubis_under_pf_11001.geometry}
        material={materials.M_anubis_head}
        skeleton={nodes.visual_anubis_under_pf_11001.skeleton}
        position={[-12.018, -9.447, 19.403]}
        rotation={[0, 1.571, 0]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_scarabeus.geometry}
        material={materials.M_scarabeus}
        skeleton={nodes.visual_scarabeus.skeleton}
        position={[-2.787, -3.823, 38.518]}
        rotation={[0, 0.036, 0]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_anubis_under_pf2001.geometry}
        material={materials.M_anubis_head}
        skeleton={nodes.visual_anubis_under_pf2001.skeleton}
        position={[7.546, -9.807, 31.689]}
        rotation={[-1.568, -1.568, -1.568]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_torch_left_24001.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_torch_left_24001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_torch_right_28001.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_torch_right_28001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_ornate_torch_01_14001.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_ornate_torch_01_14001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_ornate_torch_03_17.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_ornate_torch_03_17.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead1001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead1001.skeleton}
        position={[-0.876, 3.675, -33.212]}
        rotation={[-Math.PI, -0.806, -Math.PI]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead2_19001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead2_19001.skeleton}
        position={[13.093, 3.675, -29.937]}
        rotation={[-Math.PI, 1.394, -Math.PI]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead3001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead3001.skeleton}
        position={[-3.224, 3.675, -22.252]}
        rotation={[0, -1.312, 0]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead4_18001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead4_18001.skeleton}
        position={[10.787, 3.675, -19.151]}
        rotation={[0, 0.806, 0]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_waterlvl_bubble_2001.geometry}
        material={materials.water_level_bubble}
        skeleton={nodes.visual_waterlvl_bubble_2001.skeleton}
        position={[-1.78, -5.318, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_crocodile_plunger.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crocodile_plunger.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <skinnedMesh
          geometry={nodes.mummy_LOD0.geometry}
          material={materials.M_mummy}
          skeleton={nodes.mummy_LOD0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.mummy_LOD0_1.geometry}
          material={materials.M_mummy_eye}
          skeleton={nodes.mummy_LOD0_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.mummy_LOD0_2.geometry}
          material={materials.M_mummy_jewel}
          skeleton={nodes.mummy_LOD0_2.skeleton}
        />
      </group>
      <skinnedMesh
        geometry={nodes.visual_slingshot_left_10001.geometry}
        material={materials.rubber}
        skeleton={nodes.visual_slingshot_left_10001.skeleton}
        position={[-13.605, -3.882, 38.178]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_slingshot_right_7001.geometry}
        material={materials.rubber}
        skeleton={nodes.visual_slingshot_right_7001.skeleton}
        position={[9.735, -3.882, 38.364]}
        scale={94.51}
      />
    </group>
  );
}

useGLTF.preload("/models/PinballMVP-transformed.glb");
