/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PinballMVP_Resized.glb -t -j -o src/components/models/PinballMVPResized.tsx 
*/

import * as THREE from "three";
// import React from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { JSX } from "react";
import { RigidBody, CuboidCollider } from "@react-three/rapier";
import Flipper from "@/components/Flipper";
import Slingshot from "@/components/Slingshot";

type GLTFResult = GLTF & {
  nodes: {
    visual_ground_2: THREE.Mesh;
    visual_bg_sunset_2: THREE.Mesh;
    visual_env_pyramid: THREE.Mesh;
    visual_env_sand: THREE.Mesh;
    visual_crane: THREE.Mesh;
    visual_env_ruin_left_1: THREE.Mesh;
    visual_env_ruin_right_0: THREE.Mesh;
    env_ruins1_LOD0: THREE.Mesh;
    env_ruins1_LOD0_1: THREE.Mesh;
    oasis_vegetation_back_LOD0: THREE.Mesh;
    oasis_vegetation_back_LOD0_1: THREE.Mesh;
    oasis_vegetation_back_LOD0_2: THREE.Mesh;
    visual_oasis_vegetation_front_5: THREE.Mesh;
    visual_overlap_2: THREE.Mesh;
    mummy_button_LOD0: THREE.Mesh;
    mummy_button_LOD0_1: THREE.Mesh;
    visual_grill: THREE.Mesh;
    visual_oasis_lake_2: THREE.Mesh;
    visual_env_tools: THREE.Mesh;
    visual_nile_vegetables: THREE.Mesh;
    visual_sarcophagus01_basex: THREE.Mesh;
    visual_nile: THREE.Mesh;
    visual_habit_right_9: THREE.Mesh;
    visual_habit_left_7: THREE.Mesh;
    visual_scarab_flasher_01_16: THREE.Mesh;
    visual_scarab_flasher_02_26: THREE.Mesh;
    visual_scarab_flasher_05_18: THREE.Mesh;
    visual_scarab_flasher_plane_01_17: THREE.Mesh;
    visual_scarab_flasher_plane_02_27: THREE.Mesh;
    visual_scarab_flasher_plane_05_19: THREE.Mesh;
    visual_scarab_flasher_03_24: THREE.Mesh;
    visual_scarab_flasher_plane_03_25: THREE.Mesh;
    visual_scarab_flasher_06_20: THREE.Mesh;
    visual_scarab_flasher_07_22: THREE.Mesh;
    visual_scarab_flasher_plane_06_21: THREE.Mesh;
    visual_scarab_flasher_plane_07_23: THREE.Mesh;
    mpf_metal_wires_LOD0: THREE.Mesh;
    mpf_metal_wires_LOD0_1: THREE.Mesh;
    sphinx_1_LOD0: THREE.Mesh;
    sphinx_1_LOD0_1: THREE.Mesh;
    sphinx_2_LOD0: THREE.Mesh;
    sphinx_2_LOD0_1: THREE.Mesh;
    sphinx_3_LOD0: THREE.Mesh;
    sphinx_3_LOD0_1: THREE.Mesh;
    sphinx_7_LOD0: THREE.Mesh;
    sphinx_7_LOD0_1: THREE.Mesh;
    sphinx_8_LOD0: THREE.Mesh;
    sphinx_8_LOD0_1: THREE.Mesh;
    sphinx_base_LOD0: THREE.Mesh;
    sphinx_base_LOD0_1: THREE.Mesh;
    sphinx_6_LOD0: THREE.Mesh;
    sphinx_6_LOD0_1: THREE.Mesh;
    sphinx_4_LOD0: THREE.Mesh;
    sphinx_4_LOD0_1: THREE.Mesh;
    sphinx_5_LOD0: THREE.Mesh;
    sphinx_5_LOD0_1: THREE.Mesh;
    visual_river_water_fall: THREE.Mesh;
    visual_mummy_floor: THREE.Mesh;
    visual_overlap_bottom_3: THREE.Mesh;
    visual_lg_10x: THREE.Mesh;
    visual_lg_2x: THREE.Mesh;
    visual_lg_3x: THREE.Mesh;
    visual_lg_4x: THREE.Mesh;
    visual_lg_5x: THREE.Mesh;
    visual_lg_6x: THREE.Mesh;
    visual_lg_7x: THREE.Mesh;
    visual_lg_8x: THREE.Mesh;
    visual_lg_9x: THREE.Mesh;
    visual_locker: THREE.Mesh;
    visual_ramp_back: THREE.Mesh;
    visual_lg_crocos_c1_0: THREE.Mesh;
    visual_lg_crocos_c2_1: THREE.Mesh;
    visual_lg_crocos_o1_4: THREE.Mesh;
    visual_lg_crocos_o2_2: THREE.Mesh;
    visual_lg_crocos_r_3: THREE.Mesh;
    visual_lg_crocos_s_5: THREE.Mesh;
    visual_miniplayfield: THREE.Mesh;
    visual_obj_flipper_mini_left: THREE.Mesh;
    visual_obj_flipper_mini_left001: THREE.Mesh;
    visual_obj_flipper_mini_right: THREE.Mesh;
    visual_obj_flipper_mini_right001: THREE.Mesh;
    visual_rollover_top_1: THREE.Mesh;
    visual_rollover_top_2: THREE.Mesh;
    visual_rollover_top_3: THREE.Mesh;
    visual_droptarget_mpf_01_gfx: THREE.Mesh;
    visual_droptarget_mpf_02_gfx: THREE.Mesh;
    visual_droptarget_mpf_03_gfx: THREE.Mesh;
    visual_droptarget_mpf_04_gfx: THREE.Mesh;
    visual_droptarget_mpf_05_gfx: THREE.Mesh;
    visual_shadow_flipper_mini_right: THREE.Mesh;
    visual_shadow_flipper_mini_right001: THREE.Mesh;
    visual_river_water: THREE.Mesh;
    visual_ramp_right_sand: THREE.Mesh;
    middle_stuff_top_LOD0: THREE.Mesh;
    middle_stuff_top_LOD0_1: THREE.Mesh;
    visual_bridge_part_01: THREE.Mesh;
    visual_bridge_part_02: THREE.Mesh;
    visual_bridge_part_03: THREE.Mesh;
    visual_bridge_part_04: THREE.Mesh;
    visual_mpf_spinner_obj: THREE.Mesh;
    visual_gate_mpf_left_gfx_8: THREE.Mesh;
    visual_gate_mpf_right_gfx_3: THREE.Mesh;
    obj_target_LOD0: THREE.Mesh;
    obj_target_LOD0_1: THREE.Mesh;
    visual_obj_target001_6: THREE.Mesh;
    visual_lg_bridge_on_the_nile: THREE.Mesh;
    visual_lg_bridge_1: THREE.Mesh;
    visual_lg_sphinx_83: THREE.Mesh;
    visual_lg_underworld_86: THREE.Mesh;
    visual_lg_bonus_multi_85: THREE.Mesh;
    visual_lg_bridge_2: THREE.Mesh;
    visual_lg_lock_mpf_84: THREE.Mesh;
    visual_lg_mummy_mpf_82: THREE.Mesh;
    visual_lg_sun_clock_16: THREE.Mesh;
    visual_lg_sun_clock_18: THREE.Mesh;
    visual_lg_sun_clock_20: THREE.Mesh;
    visual_lg_sun_clock_22: THREE.Mesh;
    visual_lg_sun_clock_24: THREE.Mesh;
    visual_lg_sun_clock_26: THREE.Mesh;
    visual_lg_sun_clock_28: THREE.Mesh;
    visual_lg_sun_clock_30: THREE.Mesh;
    visual_spindisk_mpf: THREE.Mesh;
    visual_diverter_to_vuk_0: THREE.Mesh;
    visual_lg_maze_blaze_116: THREE.Mesh;
    visual_lg_scarab_trouble_5: THREE.Mesh;
    visual_lg_jackpot_92: THREE.Mesh;
    visual_lg_maze_blaze_118: THREE.Mesh;
    visual_lg_scarab_trouble_105: THREE.Mesh;
    visual_lg_army_of_anubis_70: THREE.Mesh;
    visual_lg_croco_madness_115: THREE.Mesh;
    visual_lg_croco_madness_97: THREE.Mesh;
    visual_lg_jackpot_101: THREE.Mesh;
    visual_lg_jackpot_102: THREE.Mesh;
    visual_lg_jackpot_104: THREE.Mesh;
    visual_lg_jackpot_106: THREE.Mesh;
    visual_lg_jackpot_111: THREE.Mesh;
    visual_lg_jackpot_4: THREE.Mesh;
    visual_lg_kickback_95: THREE.Mesh;
    visual_lg_lock_91: THREE.Mesh;
    visual_lg_maze_blaze_113: THREE.Mesh;
    visual_lg_mummy_100: THREE.Mesh;
    visual_lg_mummy_103: THREE.Mesh;
    visual_lg_mummy_108: THREE.Mesh;
    visual_lg_mummy_109: THREE.Mesh;
    visual_lg_mummy_114: THREE.Mesh;
    visual_lg_mummy_90: THREE.Mesh;
    visual_lg_mummy_99: THREE.Mesh;
    visual_lg_oasis_54: THREE.Mesh;
    visual_lg_palm_tree_107: THREE.Mesh;
    visual_lg_palm_tree_93: THREE.Mesh;
    visual_lg_palm_tree_98: THREE.Mesh;
    visual_lg_pyramid_64: THREE.Mesh;
    visual_lg_tomb_runner_55: THREE.Mesh;
    visual_lg_wizard_mode_62: THREE.Mesh;
    visual_lg_kickback_112: THREE.Mesh;
    visual_lg_egypt_e: THREE.Mesh;
    visual_lg_egypt_g: THREE.Mesh;
    visual_lg_egypt_y: THREE.Mesh;
    visual_lg_extra_ball_65: THREE.Mesh;
    visual_lg_jackpot_96: THREE.Mesh;
    visual_lg_mummy_87: THREE.Mesh;
    visual_lg_palm_tree_110: THREE.Mesh;
    visual_lg_palm_tree_94: THREE.Mesh;
    visual_lg_scarab_trouble_117: THREE.Mesh;
    screws_LOD0: THREE.Mesh;
    screws_LOD0_1: THREE.Mesh;
    visual_obj_flipper_left_bottom: THREE.Mesh;
    visual_obj_flipper_right_bottom: THREE.Mesh;
    visual_lg_ball_37: THREE.Mesh;
    visual_obj_gate_5: THREE.Mesh;
    visual_ramp_left_sand: THREE.Mesh;
    visual_pyramid: THREE.Mesh;
    visual_scarab_flasher_04_15: THREE.Mesh;
    visual_scarab_flasher_plane_04_14: THREE.Mesh;
    obj_spinner_LOD0: THREE.Mesh;
    obj_spinner_LOD0_1: THREE.Mesh;
    visual_lg_gi_lamps_4: THREE.Mesh;
    GI_bulbs_gfx_LOD0: THREE.Mesh;
    GI_bulbs_gfx_LOD0_1: THREE.Mesh;
    visual_middle_stuff_overlap: THREE.Mesh;
    visual_slingshot_flash_obj_left: THREE.Mesh;
    visual_slingshot_flash_obj_right: THREE.Mesh;
    visual_stared_posts: THREE.Mesh;
    visual_screws_slingshots: THREE.Mesh;
    visual_lg_kickback_right_36: THREE.Mesh;
    visual_metals_slingshot: THREE.Mesh;
    visual_slingshot_right_shot: THREE.Mesh;
    visual_slingshot_left_shot: THREE.Mesh;
    visual_lg_kickback_left_40: THREE.Mesh;
    visual_lg_egypt_p: THREE.Mesh;
    visual_lg_egypt_t: THREE.Mesh;
    visual_metal_post_outlanes_up: THREE.Mesh;
    visual_sidewalls: THREE.Mesh;
    visual_right_kickback_door: THREE.Mesh;
    visual_diverter_plunger_back: THREE.Mesh;
    visual_diverter_plunger: THREE.Mesh;
    holes_nocoll_LOD0: THREE.Mesh;
    holes_nocoll_LOD0_1: THREE.Mesh;
    waterlvl_LOD0: THREE.Mesh;
    waterlvl_LOD0_1: THREE.Mesh;
    waterlvl_LOD0_2: THREE.Mesh;
    visual_ball_rollover: THREE.Mesh;
    visual_bonus_04: THREE.Mesh;
    visual_bonus_05: THREE.Mesh;
    visual_bonus_01: THREE.Mesh;
    visual_bonus_02: THREE.Mesh;
    visual_bonus_03: THREE.Mesh;
    posts_outlane_LOD0: THREE.Mesh;
    posts_outlane_LOD0_1: THREE.Mesh;
    visual_playfield: THREE.Mesh;
    visual_diverter_left_orbit_1: THREE.Mesh;
    visual_pf_door_right: THREE.Mesh;
    visual_pf_door_left: THREE.Mesh;
    visual_under_pf: THREE.Mesh;
    visual_anu_card_01_gfx: THREE.Mesh;
    visual_anu_card_02_gfx: THREE.Mesh;
    visual_anu_card_03_gfx: THREE.Mesh;
    visual_anu_card_04_gfx: THREE.Mesh;
    visual_anu_card_05_gfx: THREE.Mesh;
    visual_lg_army_of_anubis_02: THREE.Mesh;
    visual_plunger: THREE.Mesh;
    visual_diverter_right_orbit: THREE.Mesh;
    visual_diverter_center03: THREE.Mesh;
    visual_diverter_center01: THREE.Mesh;
    visual_diverter_center02_21: THREE.Mesh;
    coll_habit_left: THREE.Mesh;
    coll_habit_mini_pf: THREE.Mesh;
    coll_habit_right: THREE.Mesh;
    coll_ramp_back: THREE.Mesh;
    coll_top: THREE.Mesh;
    coll_standard_collision: THREE.Mesh;
    coll_habit_vuk: THREE.Mesh;
    coll_sphinx_bottom: THREE.Mesh;
    coll_locker: THREE.Mesh;
    coll_ramp_back001: THREE.Mesh;
    coll_flipper_mini_left: THREE.Mesh;
    coll_flipper_mini_left001: THREE.Mesh;
    coll_flipper_mini_right: THREE.Mesh;
    coll_flipper_mini_right001: THREE.Mesh;
    coll_bumper01: THREE.Mesh;
    coll_bumper02: THREE.Mesh;
    coll_bumper03: THREE.Mesh;
    coll_bumper04: THREE.Mesh;
    coll_locker_launch: THREE.Mesh;
    coll_mpf_spindisk_wall: THREE.Mesh;
    coll_blunt_rubber: THREE.Mesh;
    coll_droptarget_mpf_01: THREE.Mesh;
    coll_droptarget_mpf_02: THREE.Mesh;
    coll_droptarget_mpf_03: THREE.Mesh;
    coll_droptarget_mpf_04: THREE.Mesh;
    coll_droptarget_mpf_05: THREE.Mesh;
    coll_mpf_metal_wires: THREE.Mesh;
    coll_scoops01_6: THREE.Mesh;
    coll_ramp_right: THREE.Mesh;
    coll_rubber: THREE.Mesh;
    coll_super_rubber: THREE.Mesh;
    coll_nile: THREE.Mesh;
    coll_mpf_spinner: THREE.Mesh;
    coll_miniplayfield: THREE.Mesh;
    coll_bridge_part_01: THREE.Mesh;
    coll_bridge_part_02: THREE.Mesh;
    coll_bridge_part_03: THREE.Mesh;
    coll_bridge_part_04: THREE.Mesh;
    coll_gate_mpf_left: THREE.Mesh;
    coll_gate_mpf_right_2: THREE.Mesh;
    coll_target: THREE.Mesh;
    coll_target001: THREE.Mesh;
    coll_spindisk_mpf: THREE.Mesh;
    coll_diverter_to_vuk: THREE.Mesh;
    coll_flipper_left_bottom: THREE.Mesh;
    coll_flipper_right_bottom: THREE.Mesh;
    coll_gate: THREE.Mesh;
    coll_safe_pyramid: THREE.Mesh;
    coll_pyramid: THREE.Mesh;
    coll_pyramid_temporary: THREE.Mesh;
    coll_pyramid_wall_03: THREE.Mesh;
    coll_pyramid_door: THREE.Mesh;
    coll_spinner_10: THREE.Mesh;
    coll_metal: THREE.Mesh;
    coll_scoops: THREE.Mesh;
    coll_ramp_left: THREE.Mesh;
    coll_anubis_head_hole: THREE.Mesh;
    coll_fr_slingshot_flasher_left: THREE.Mesh;
    coll_fr_slingshot_flasher_right: THREE.Mesh;
    coll_ramp_metal: THREE.Mesh;
    coll_sidewalls: THREE.Mesh;
    coll_left_kickback_door: THREE.Mesh;
    coll_diverter_plunger_back: THREE.Mesh;
    coll_diverter_plunger: THREE.Mesh;
    coll_anubis_mouth: THREE.Mesh;
    coll_posts_outlane: THREE.Mesh;
    coll_playfield_collision: THREE.Mesh;
    coll_left_hole: THREE.Mesh;
    coll_diverter_left_orbit_0: THREE.Mesh;
    coll_under_pf: THREE.Mesh;
    coll_anu_card_01: THREE.Mesh;
    coll_anu_card_02: THREE.Mesh;
    coll_anu_card_03: THREE.Mesh;
    coll_anu_card_04: THREE.Mesh;
    coll_anu_card_05: THREE.Mesh;
    coll_diverter_right_orbit: THREE.Mesh;
    coll_diverter_center02_20: THREE.Mesh;
    coll_diverter_center03: THREE.Mesh;
    coll_diverter_center01: THREE.Mesh;
    coll_right_sling_collision_bottom: THREE.Mesh;
    coll_left_sling_collision_bottom: THREE.Mesh;
    coll_left_sling_collision_top: THREE.Mesh;
    coll_right_sling_collision_top: THREE.Mesh;
    sensor_mpf_presence_0: THREE.Mesh;
    sensor_mini_left001_arm: THREE.Mesh;
    sensor_mini_left_arm: THREE.Mesh;
    sensor_mini_right001_arm: THREE.Mesh;
    sensor_mini_right_arm: THREE.Mesh;
    sensor_nile: THREE.Mesh;
    sensor_bridge_left: THREE.Mesh;
    sensor_bridge_right: THREE.Mesh;
    sensor_bridge: THREE.Mesh;
    sensor_left_bottom_arm: THREE.Mesh;
    sensor_right_bottom_arm: THREE.Mesh;
    stick_barrier: THREE.Mesh;
    TrialHoleDrainSensor: THREE.Mesh;
    launched: THREE.Mesh;
    sensor_sinkhole_left: THREE.Mesh;
    visual_crocodile_plunger: THREE.Mesh;
    visual_anubis: THREE.Mesh;
    visual_ornate_torch_04_20: THREE.Mesh;
    coll_locker_door_2001: THREE.Mesh;
    visual_locker_door_2: THREE.Mesh;
    visual_sarcophagus01_door_3001: THREE.Mesh;
    visual_anubis_under_pf_11001: THREE.Mesh;
    visual_anubis_under_pf2001: THREE.Mesh;
    visual_torch_left_24001: THREE.Mesh;
    visual_torch_right_28001: THREE.Mesh;
    visual_ornate_torch_01_14001: THREE.Mesh;
    visual_ornate_torch_03_17: THREE.Mesh;
    visual_crochead1001: THREE.Mesh;
    visual_crochead2_19001: THREE.Mesh;
    visual_crochead3001: THREE.Mesh;
    visual_crochead4_18001: THREE.Mesh;
    visual_slingshot_left_10001: THREE.Mesh;
    visual_slingshot_right_7001: THREE.Mesh;
    visual_waterlvl_bubble_2001: THREE.Mesh;
  };
  materials: {
    M_sand_tile: THREE.MeshStandardMaterial;
    M_bg_sunset: THREE.MeshStandardMaterial;
    M_env_pyramid: THREE.MeshStandardMaterial;
    M_bg_env_ground: THREE.MeshStandardMaterial;
    M_crane: THREE.MeshStandardMaterial;
    M_overlap: THREE.MeshStandardMaterial;
    M_ruin_right: THREE.MeshStandardMaterial;
    M_env_ruins1: THREE.MeshStandardMaterial;
    M_broken_stone1: THREE.MeshStandardMaterial;
    M_vegetation: THREE.MeshStandardMaterial;
    M_palm_bark: THREE.MeshStandardMaterial;
    M_vegetation1: THREE.MeshStandardMaterial;
    M_mummy_button: THREE.MeshStandardMaterial;
    M_mummy_button_alpha: THREE.MeshStandardMaterial;
    M_water_plunger: THREE.MeshStandardMaterial;
    M_env_tools: THREE.MeshStandardMaterial;
    M_vegetation_02: THREE.MeshStandardMaterial;
    M_sarcophagus: THREE.MeshStandardMaterial;
    M_nile_ramp: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    scarab_flasher: THREE.MeshStandardMaterial;
    lamp_scarab_flasher: THREE.MeshStandardMaterial;
    rubber: THREE.MeshStandardMaterial;
    M_sphinx: THREE.MeshStandardMaterial;
    M_broken_stone: THREE.MeshStandardMaterial;
    M_water_river: THREE.MeshStandardMaterial;
    m_mummy_path: THREE.MeshStandardMaterial;
    lamp_playfield: THREE.MeshStandardMaterial;
    M_locker: THREE.MeshStandardMaterial;
    M_ramp_back: THREE.MeshStandardMaterial;
    M_miniplayfield: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_left: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_left2: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_right: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_right2: THREE.MeshStandardMaterial;
    M_midlestuff: THREE.MeshStandardMaterial;
    flipper_arms_shadow: THREE.MeshStandardMaterial;
    M_ramps: THREE.MeshStandardMaterial;
    ["rubber.001"]: THREE.MeshStandardMaterial;
    M_bridge: THREE.MeshStandardMaterial;
    ["chrome.001"]: THREE.MeshStandardMaterial;
    target: THREE.MeshStandardMaterial;
    ["metal_sidewalls.001"]: THREE.MeshStandardMaterial;
    M_spindisk: THREE.MeshStandardMaterial;
    M_flipper_arm_left: THREE.MeshStandardMaterial;
    M_flipper_arm_right: THREE.MeshStandardMaterial;
    M_pyramid__Inst: THREE.MeshStandardMaterial;
    M_spinner: THREE.MeshStandardMaterial;
    lamp_playfield_white: THREE.MeshStandardMaterial;
    lightbulbs_Inst: THREE.MeshStandardMaterial;
    M_slingshot_flasher_obj: THREE.MeshStandardMaterial;
    M_stared_post: THREE.MeshStandardMaterial;
    metal_sidewalls: THREE.MeshStandardMaterial;
    ["M_overlap.001"]: THREE.MeshStandardMaterial;
    ["M_playfield_cutout.001"]: THREE.MeshStandardMaterial;
    M_black: THREE.MeshStandardMaterial;
    gold: THREE.MeshStandardMaterial;
    waterlvl: THREE.MeshStandardMaterial;
    chrome_low: THREE.MeshStandardMaterial;
    playfield: THREE.MeshStandardMaterial;
    M_underplayfield: THREE.MeshStandardMaterial;
    M_army_of_anubis: THREE.MeshStandardMaterial;
    M_anubis_head_eyes: THREE.MeshStandardMaterial;
    collision: THREE.MeshStandardMaterial;
    M_slingshot_flasher_emissive: THREE.MeshStandardMaterial;
    sensors: THREE.MeshStandardMaterial;
    M_crocodile_plunger: THREE.MeshStandardMaterial;
    M_anubis_head: THREE.MeshStandardMaterial;
    M_Torches: THREE.MeshStandardMaterial;
    M_anubis_head_mpf: THREE.MeshStandardMaterial;
    water_level_bubble: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export default function PinballMVP(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/PinballMVP_Resized.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.visual_ground_2.geometry}
        material={materials.M_sand_tile}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_bg_sunset_2.geometry}
        material={materials.M_bg_sunset}
        position={[-0.609, 3.262, -91.71]}
      />
      <mesh
        geometry={nodes.visual_env_pyramid.geometry}
        material={materials.M_env_pyramid}
        position={[-49.904, 11.73, -40.039]}
      />
      <mesh
        geometry={nodes.visual_env_sand.geometry}
        material={materials.M_bg_env_ground}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_crane.geometry}
        material={materials.M_crane}
        position={[27.797, 3.521, 21.237]}
      />
      <mesh
        geometry={nodes.visual_env_ruin_left_1.geometry}
        material={materials.M_overlap}
        position={[-18.208, 1.757, 16.697]}
      />
      <mesh
        geometry={nodes.visual_env_ruin_right_0.geometry}
        material={materials.M_ruin_right}
        position={[24.894, 1.147, -0.857]}
      />
      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.env_ruins1_LOD0.geometry}
          material={materials.M_env_ruins1}
        />
        <mesh
          geometry={nodes.env_ruins1_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0.geometry}
          material={materials.M_vegetation}
          material-alphaTest={0.02}
        />
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0_1.geometry}
          material={materials.M_palm_bark}
          material-alphaTest={0.02}
        />
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0_2.geometry}
          material={materials.M_vegetation1}
          material-alphaTest={0.02}
        />
      </group>
      <mesh
        geometry={nodes.visual_oasis_vegetation_front_5.geometry}
        material={materials.M_vegetation}
        position={[-0.609, -2.903, 5.131]}
        material-alphaTest={0.02}
      />
      <mesh
        geometry={nodes.visual_overlap_2.geometry}
        material={materials.M_overlap}
        position={[-0.609, -2.903, 5.131]}
      />
      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.mummy_button_LOD0.geometry}
          material={materials.M_mummy_button}
        />
        <mesh
          geometry={nodes.mummy_button_LOD0_1.geometry}
          material={materials.M_mummy_button_alpha}
        />
      </group>
      <mesh
        geometry={nodes.visual_grill.geometry}
        material={materials.M_ruin_right}
        position={[17.009, -1.431, 28.598]}
      />
      <mesh
        geometry={nodes.visual_oasis_lake_2.geometry}
        material={materials.M_water_plunger}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_env_tools.geometry}
        material={materials.M_env_tools}
        position={[-7.463, -1.367, 29.56]}
      />
      <mesh
        geometry={nodes.visual_nile_vegetables.geometry}
        material={materials.M_vegetation_02}
        position={[2.268, 1.58, -13.395]}
        material-alphaTest={0.02}
      />
      <mesh
        geometry={nodes.visual_sarcophagus01_basex.geometry}
        material={materials.M_sarcophagus}
        position={[13.477, 2.046, -1.653]}
      />
      <mesh
        geometry={nodes.visual_nile.geometry}
        material={materials.M_nile_ramp}
        position={[2.268, 1.58, -13.395]}
      />
      <mesh
        geometry={nodes.visual_habit_right_9.geometry}
        material={materials.chrome}
        position={[-0.622, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_habit_left_7.geometry}
        material={materials.chrome}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_01_16.geometry}
        material={materials.scarab_flasher}
        position={[-12.673, 1.436, 5.558]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_02_26.geometry}
        material={materials.scarab_flasher}
        position={[8.638, -1.119, 10.026]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_05_18.geometry}
        material={materials.scarab_flasher}
        position={[-15.801, -1.095, -10.473]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_01_17.geometry}
        material={materials.lamp_scarab_flasher}
        position={[-12.723, 1.597, 5.562]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_02_27.geometry}
        material={materials.lamp_scarab_flasher}
        position={[8.691, -0.928, 10.017]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_05_19.geometry}
        material={materials.lamp_scarab_flasher}
        position={[-15.79, -0.88, -10.491]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_03_24.geometry}
        material={materials.scarab_flasher}
        position={[9.823, -1.136, -12.309]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_03_25.geometry}
        material={materials.lamp_scarab_flasher}
        position={[9.9, -0.976, -12.321]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_06_20.geometry}
        material={materials.scarab_flasher}
        position={[-4.985, 4.612, -18.978]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_07_22.geometry}
        material={materials.scarab_flasher}
        position={[9.819, 4.769, -16.55]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_06_21.geometry}
        material={materials.lamp_scarab_flasher}
        position={[-5.023, 4.773, -18.987]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_07_23.geometry}
        material={materials.lamp_scarab_flasher}
        position={[9.846, 4.93, -16.563]}
      />
      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.mpf_metal_wires_LOD0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.mpf_metal_wires_LOD0_1.geometry}
          material={materials.rubber}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_1_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_1_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_2_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_2_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_3_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_3_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_7_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_7_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_8_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_8_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_base_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_base_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_6_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_6_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_4_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_4_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <group position={[-7.805, 3.117, -19.057]} rotation={[0, 0.41, 0]}>
        <mesh
          geometry={nodes.sphinx_5_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_5_LOD0_1.geometry}
          material={materials.M_broken_stone}
        />
      </group>
      <mesh
        geometry={nodes.visual_river_water_fall.geometry}
        material={materials.M_water_river}
        position={[0.725, -0.855, -4.398]}
      />
      <mesh
        geometry={nodes.visual_mummy_floor.geometry}
        material={materials.m_mummy_path}
        position={[11.672, -1.618, 18.099]}
      />
      <mesh
        geometry={nodes.visual_overlap_bottom_3.geometry}
        material={materials.M_overlap}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_lg_10x.geometry}
        material={materials.lamp_playfield}
        position={[9.292, -1.447, 25.651]}
      />
      <mesh
        geometry={nodes.visual_lg_2x.geometry}
        material={materials.lamp_playfield}
        position={[0.924, -1.401, 30.58]}
      />
      <mesh
        geometry={nodes.visual_lg_3x.geometry}
        material={materials.lamp_playfield}
        position={[1.992, -1.377, 30.17]}
      />
      <mesh
        geometry={nodes.visual_lg_4x.geometry}
        material={materials.lamp_playfield}
        position={[3.144, -1.377, 29.57]}
      />
      <mesh
        geometry={nodes.visual_lg_5x.geometry}
        material={materials.lamp_playfield}
        position={[4.085, -1.419, 28.91]}
      />
      <mesh
        geometry={nodes.visual_lg_6x.geometry}
        material={materials.lamp_playfield}
        position={[5.183, -1.425, 28.271]}
      />
      <mesh
        geometry={nodes.visual_lg_7x.geometry}
        material={materials.lamp_playfield}
        position={[6.097, -1.407, 27.7]}
      />
      <mesh
        geometry={nodes.visual_lg_8x.geometry}
        material={materials.lamp_playfield}
        position={[7.2, -1.384, 27.003]}
      />
      <mesh
        geometry={nodes.visual_lg_9x.geometry}
        material={materials.lamp_playfield}
        position={[8.219, -1.391, 26.367]}
      />
      <mesh
        geometry={nodes.visual_locker.geometry}
        material={materials.M_locker}
        position={[6.704, 5.383, -17.78]}
      />
      <mesh
        geometry={nodes.visual_ramp_back.geometry}
        material={materials.M_ramp_back}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_c1_0.geometry}
        material={materials.lamp_playfield}
        position={[0.168, 5.701, -22.084]}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_c2_1.geometry}
        material={materials.lamp_playfield}
        position={[0.177, 4.712, -22.081]}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_o1_4.geometry}
        material={materials.lamp_playfield}
        position={[4.033, 5.703, -22.091]}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_o2_2.geometry}
        material={materials.lamp_playfield}
        position={[2.101, 4.719, -22.112]}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_r_3.geometry}
        material={materials.lamp_playfield}
        position={[2.075, 5.713, -22.112]}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_s_5.geometry}
        material={materials.lamp_playfield}
        position={[4.045, 4.705, -22.091]}
      />
      <mesh
        geometry={nodes.visual_miniplayfield.geometry}
        material={materials.M_miniplayfield}
        position={[-1.256, 3.151, -16.458]}
      />
      <mesh
        geometry={nodes.visual_rollover_top_1.geometry}
        material={materials.chrome}
        position={[-0.152, 3.237, -20.829]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        geometry={nodes.visual_rollover_top_2.geometry}
        material={materials.chrome}
        position={[2.243, 3.237, -20.862]}
      />
      <mesh
        geometry={nodes.visual_rollover_top_3.geometry}
        material={materials.chrome}
        position={[4.667, 3.237, -20.824]}
        rotation={[0, -0.279, 0]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_01_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-8.61, 2.886, -14.238]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_02_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-8.751, 2.886, -14.482]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_03_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-8.892, 2.886, -14.727]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_04_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-9.034, 2.886, -14.972]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_05_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-9.175, 2.886, -15.217]}
        rotation={[0, Math.PI / 6, 0]}
      />
      <mesh
        geometry={nodes.visual_shadow_flipper_mini_right.geometry}
        material={materials.flipper_arms_shadow}
        position={[-1.438, 3.171, -10.792]}
        rotation={[0, 0.96, Math.PI]}
      />
      <mesh
        geometry={nodes.visual_shadow_flipper_mini_right001.geometry}
        material={materials.flipper_arms_shadow}
        position={[10.799, 3.171, -9.674]}
        rotation={[0, 0.367, Math.PI]}
      />
      <mesh
        geometry={nodes.visual_river_water.geometry}
        material={materials.M_water_river}
        position={[2.423, 1.235, -13.226]}
      />
      <mesh
        geometry={nodes.visual_ramp_right_sand.geometry}
        material={materials.M_ramps}
        position={[-0.609, -2.903, 5.131]}
      />
      <group position={[-1.969, -1.485, -1.899]}>
        <mesh
          geometry={nodes.middle_stuff_top_LOD0.geometry}
          material={materials.M_midlestuff}
        />
        <mesh
          geometry={nodes.middle_stuff_top_LOD0_1.geometry}
          material={materials["rubber.001"]}
        />
      </group>
      <mesh
        geometry={nodes.visual_bridge_part_01.geometry}
        material={materials.M_bridge}
        position={[-0.02, 3.123, -14.224]}
        rotation={[0, 0.122, 0]}
      />
      <mesh
        geometry={nodes.visual_bridge_part_02.geometry}
        material={materials.M_bridge}
        position={[1.061, 3.123, -14.326]}
        rotation={[0, 0.105, 0]}
      />
      <mesh
        geometry={nodes.visual_bridge_part_03.geometry}
        material={materials.M_bridge}
        position={[2.142, 3.123, -14.274]}
        rotation={[0, 0.087, 0]}
      />
      <mesh
        geometry={nodes.visual_bridge_part_04.geometry}
        material={materials.M_bridge}
        position={[3.224, 3.123, -14.043]}
        rotation={[0, 0.07, 0]}
      />
      <mesh
        geometry={nodes.visual_mpf_spinner_obj.geometry}
        material={materials["chrome.001"]}
        position={[-2.597, 3.151, -17.494]}
        rotation={[0, -1.309, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.visual_gate_mpf_left_gfx_8.geometry}
        material={materials["chrome.001"]}
        position={[-1.267, 5.006, -21.296]}
        rotation={[Math.PI / 2, 0, 1.466]}
      />
      <mesh
        geometry={nodes.visual_gate_mpf_right_gfx_3.geometry}
        material={materials["chrome.001"]}
        position={[6.037, 5.006, -21.217]}
        rotation={[Math.PI / 2, 0, -1.431]}
      />
      <group
        position={[9.628, 3.158, -15.479]}
        rotation={[3.141, -1.32, 3.141]}
      >
        <mesh
          geometry={nodes.obj_target_LOD0.geometry}
          material={materials.target}
        />
        <mesh
          geometry={nodes.obj_target_LOD0_1.geometry}
          material={materials["chrome.001"]}
        />
      </group>
      <mesh
        geometry={nodes.visual_obj_target001_6.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[11.948, 3.158, -13.172]}
        rotation={[3.142, -0.465, 3.142]}
      />
      <mesh
        geometry={nodes.visual_lg_bridge_on_the_nile.geometry}
        material={materials.lamp_playfield}
        position={[-1.817, 3.175, -13.142]}
        rotation={[0, 0.262, 0]}
      />
      <mesh
        geometry={nodes.visual_lg_bridge_1.geometry}
        material={materials.lamp_playfield}
        position={[-1.702, 3.165, -13.639]}
      />
      <mesh
        geometry={nodes.visual_lg_sphinx_83.geometry}
        material={materials.lamp_playfield}
        position={[-5.505, 3.165, -13.853]}
      />
      <mesh
        geometry={nodes.visual_lg_underworld_86.geometry}
        material={materials.lamp_playfield}
        position={[-7.917, 3.165, -12.858]}
      />
      <mesh
        geometry={nodes.visual_lg_bonus_multi_85.geometry}
        material={materials.lamp_playfield}
        position={[10.926, 3.165, -12.502]}
      />
      <mesh
        geometry={nodes.visual_lg_bridge_2.geometry}
        material={materials.lamp_playfield}
        position={[6.098, 3.165, -13.253]}
      />
      <mesh
        geometry={nodes.visual_lg_lock_mpf_84.geometry}
        material={materials.lamp_playfield}
        position={[8.012, 3.165, -15.063]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_mpf_82.geometry}
        material={materials.lamp_playfield}
        position={[6.374, 3.165, -14.858]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_16.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_18.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_20.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_22.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_24.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_26.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_28.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
        rotation={[0, -Math.PI / 4, 0]}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_30.geometry}
        material={materials.lamp_playfield}
        position={[-2.597, 3.151, -17.494]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        geometry={nodes.visual_spindisk_mpf.geometry}
        material={materials.M_spindisk}
        position={[-2.597, 3.151, -17.494]}
      />
      <mesh
        geometry={nodes.visual_diverter_to_vuk_0.geometry}
        material={materials.M_ramp_back}
        position={[12.743, -2.903, -9.297]}
      />
      <mesh
        geometry={nodes.visual_lg_maze_blaze_116.geometry}
        material={materials.lamp_playfield}
        position={[8.25, -2.888, 3.1]}
      />
      <mesh
        geometry={nodes.visual_lg_scarab_trouble_5.geometry}
        material={materials.lamp_playfield}
        position={[5.547, -2.888, 2.999]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_92.geometry}
        material={materials.lamp_playfield}
        position={[0.33, -2.888, -1.678]}
      />
      <mesh
        geometry={nodes.visual_lg_maze_blaze_118.geometry}
        material={materials.lamp_playfield}
        position={[0.948, -2.883, -6.952]}
      />
      <mesh
        geometry={nodes.visual_lg_scarab_trouble_105.geometry}
        material={materials.lamp_playfield}
        position={[0.695, -2.899, -4.424]}
      />
      <mesh
        geometry={nodes.visual_lg_army_of_anubis_70.geometry}
        material={materials.lamp_playfield}
        position={[4.475, -2.888, 5.371]}
      />
      <mesh
        geometry={nodes.visual_lg_croco_madness_115.geometry}
        material={materials.lamp_playfield}
        position={[-7.126, -2.888, 7.233]}
      />
      <mesh
        geometry={nodes.visual_lg_croco_madness_97.geometry}
        material={materials.lamp_playfield}
        position={[6.171, -2.888, 8.145]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_101.geometry}
        material={materials.lamp_playfield}
        position={[-6.9, -2.888, 1.201]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_102.geometry}
        material={materials.lamp_playfield}
        position={[3.522, -2.888, 7.896]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_104.geometry}
        material={materials.lamp_playfield}
        position={[-9.51, -2.888, 2.567]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_106.geometry}
        material={materials.lamp_playfield}
        position={[2.96, -2.888, 1.198]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_111.geometry}
        material={materials.lamp_playfield}
        position={[7.096, -2.888, 5.634]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_4.geometry}
        material={materials.lamp_playfield}
        position={[-4.598, -2.888, 0.867]}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_95.geometry}
        material={materials.lamp_playfield}
        position={[-7.479, -2.888, -0.877]}
      />
      <mesh
        geometry={nodes.visual_lg_lock_91.geometry}
        material={materials.lamp_playfield}
        position={[-2.447, -2.888, -2.485]}
      />
      <mesh
        geometry={nodes.visual_lg_maze_blaze_113.geometry}
        material={materials.lamp_playfield}
        position={[-10.692, -2.888, 0.036]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_100.geometry}
        material={materials.lamp_playfield}
        position={[2.68, -2.888, 10.23]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_103.geometry}
        material={materials.lamp_playfield}
        position={[-2.285, -2.888, -0.324]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_108.geometry}
        material={materials.lamp_playfield}
        position={[-6.566, -2.888, 9.347]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_109.geometry}
        material={materials.lamp_playfield}
        position={[5.142, -2.888, 9.998]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_114.geometry}
        material={materials.lamp_playfield}
        position={[1.884, -2.888, 5.563]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_90.geometry}
        material={materials.lamp_playfield}
        position={[0.082, -2.888, 0.851]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_99.geometry}
        material={materials.lamp_playfield}
        position={[-6.248, -2.888, 3.64]}
      />
      <mesh
        geometry={nodes.visual_lg_oasis_54.geometry}
        material={materials.lamp_playfield}
        position={[2.477, -2.888, 3.469]}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_107.geometry}
        material={materials.lamp_playfield}
        position={[4.429, -2.888, 11.864]}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_93.geometry}
        material={materials.lamp_playfield}
        position={[1.478, -2.888, 7.515]}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_98.geometry}
        material={materials.lamp_playfield}
        position={[-5.599, -2.888, 5.47]}
      />
      <mesh
        geometry={nodes.visual_lg_pyramid_64.geometry}
        material={materials.lamp_playfield}
        position={[-4.928, -2.888, -2.01]}
      />
      <mesh
        geometry={nodes.visual_lg_tomb_runner_55.geometry}
        material={materials.lamp_playfield}
        position={[-8.33, -2.888, 4.936]}
      />
      <mesh
        geometry={nodes.visual_lg_wizard_mode_62.geometry}
        material={materials.lamp_playfield}
        position={[-2.111, -2.888, 1.881]}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_112.geometry}
        material={materials.lamp_playfield}
        position={[3.452, -2.888, -0.891]}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_e.geometry}
        material={materials.lamp_playfield}
        position={[-13.565, -2.888, 14.649]}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_g.geometry}
        material={materials.lamp_playfield}
        position={[-11.563, -2.888, 14.647]}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_y.geometry}
        material={materials.lamp_playfield}
        position={[-9.532, -2.888, 14.649]}
      />
      <mesh
        geometry={nodes.visual_lg_extra_ball_65.geometry}
        material={materials.lamp_playfield}
        position={[-10.626, -2.888, 11.468]}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_96.geometry}
        material={materials.lamp_playfield}
        position={[-9.226, -2.888, 10.439]}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_87.geometry}
        material={materials.lamp_playfield}
        position={[-7.893, -2.888, 12.575]}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_110.geometry}
        material={materials.lamp_playfield}
        position={[-5.696, -2.888, 11.071]}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_94.geometry}
        material={materials.lamp_playfield}
        position={[-6.752, -2.888, 14.086]}
      />
      <mesh
        geometry={nodes.visual_lg_scarab_trouble_117.geometry}
        material={materials.lamp_playfield}
        position={[-10.855, -2.888, 8.036]}
      />
      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.screws_LOD0.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.screws_LOD0_1.geometry}
          material={materials.rubber}
        />
      </group>

      <mesh
        geometry={nodes.visual_lg_ball_37.geometry}
        material={materials.lamp_playfield}
        position={[-1.092, -2.888, 27.408]}
      />
      <mesh
        geometry={nodes.visual_obj_gate_5.geometry}
        material={materials["chrome.001"]}
        position={[8.733, -1.018, 5.992]}
        rotation={[Math.PI / 2, 0, -1.204]}
      />
      <mesh
        geometry={nodes.visual_ramp_left_sand.geometry}
        material={materials.M_ramps}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_pyramid.geometry}
        material={materials.M_pyramid__Inst}
        position={[-4.314, -2.903, -6.725]}
        rotation={[0, 0.175, 0]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_04_15.geometry}
        material={materials.scarab_flasher}
        position={[-3.393, -0.715, -10.768]}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_04_14.geometry}
        material={materials.lamp_scarab_flasher}
        position={[-3.428, -0.554, -10.778]}
      />
      <group
        position={[-11.326, -1.294, -1.815]}
        rotation={[Math.PI / 2, 0, 2.827]}
      >
        <mesh
          geometry={nodes.obj_spinner_LOD0.geometry}
          material={materials["chrome.001"]}
        />
        <mesh
          geometry={nodes.obj_spinner_LOD0_1.geometry}
          material={materials.M_spinner}
        />
      </group>
      <mesh
        geometry={nodes.visual_lg_gi_lamps_4.geometry}
        material={materials.lamp_playfield_white}
        position={[-0.609, -2.903, 5.131]}
      />
      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.GI_bulbs_gfx_LOD0.geometry}
          material={materials["chrome.001"]}
        />
        <mesh
          geometry={nodes.GI_bulbs_gfx_LOD0_1.geometry}
          material={materials.lightbulbs_Inst}
        />
      </group>
      <mesh
        geometry={nodes.visual_middle_stuff_overlap.geometry}
        material={materials.M_midlestuff}
        position={[-2.095, -1.532, 21.426]}
      />
      <mesh
        geometry={nodes.visual_slingshot_flash_obj_left.geometry}
        material={materials.M_slingshot_flasher_obj}
        position={[-7.408, -1.169, 18.044]}
      />
      <mesh
        geometry={nodes.visual_slingshot_flash_obj_right.geometry}
        material={materials.M_slingshot_flasher_obj}
        position={[5.178, -1.169, 18.044]}
      />
      <mesh
        geometry={nodes.visual_stared_posts.geometry}
        material={materials.M_stared_post}
        position={[-1.109, -2.292, 19.416]}
      />
      <mesh
        geometry={nodes.visual_screws_slingshots.geometry}
        material={materials["chrome.001"]}
        position={[-1.108, -1.247, 19.416]}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_right_36.geometry}
        material={materials.lamp_playfield}
        position={[9.32, -2.888, 22.524]}
      />
      <mesh
        geometry={nodes.visual_metals_slingshot.geometry}
        material={materials["chrome.001"]}
        position={[-1.086, -2.447, 19.386]}
      />
      <mesh
        geometry={nodes.visual_slingshot_right_shot.geometry}
        material={materials["chrome.001"]}
        position={[4.932, -3.315, 19.383]}
        rotation={[0, -Math.PI / 9, 0]}
      />
      <mesh
        geometry={nodes.visual_slingshot_left_shot.geometry}
        material={materials["chrome.001"]}
        position={[-7.147, -3.315, 19.383]}
        rotation={[Math.PI / 2, 0, -Math.PI / 9]}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_left_40.geometry}
        material={materials.lamp_playfield}
        position={[-13.573, -2.888, 21.273]}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_p.geometry}
        material={materials.lamp_playfield}
        position={[7.31, -2.888, 14.644]}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_t.geometry}
        material={materials.lamp_playfield}
        position={[9.292, -2.888, 14.642]}
      />
      <mesh
        geometry={nodes.visual_metal_post_outlanes_up.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-2.138, -1.91, 23.49]}
      />
      <mesh
        geometry={nodes.visual_sidewalls.geometry}
        material={materials.metal_sidewalls}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_right_kickback_door.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[8.532, -1.97, 25.481]}
        rotation={[Math.PI, -1.187, Math.PI]}
      />
      <mesh
        geometry={nodes.visual_diverter_plunger_back.geometry}
        material={materials.metal_sidewalls}
        position={[-0.693, -2.903, 0.222]}
      />
      <mesh
        geometry={nodes.visual_diverter_plunger.geometry}
        material={materials["M_overlap.001"]}
        position={[7.347, -5.606, 12.008]}
      />

      <group position={[-0.609, -2.903, 5.131]}>
        <mesh
          geometry={nodes.waterlvl_LOD0.geometry}
          material={materials.gold}
        />
        <mesh
          geometry={nodes.waterlvl_LOD0_1.geometry}
          material={materials["chrome.001"]}
        />
        <mesh
          geometry={nodes.waterlvl_LOD0_2.geometry}
          material={materials.waterlvl}
        />
      </group>
      <mesh
        geometry={nodes.visual_ball_rollover.geometry}
        material={materials.chrome}
        position={[12.739, -2.83, 28.136]}
      />
      <mesh
        geometry={nodes.visual_bonus_04.geometry}
        material={materials.chrome_low}
        position={[7.358, -2.826, 16.868]}
      />
      <mesh
        geometry={nodes.visual_bonus_05.geometry}
        material={materials.chrome}
        position={[9.354, -2.826, 16.868]}
      />
      <mesh
        geometry={nodes.visual_bonus_01.geometry}
        material={materials.chrome}
        position={[-13.585, -2.826, 16.868]}
      />
      <mesh
        geometry={nodes.visual_bonus_02.geometry}
        material={materials.chrome}
        position={[-11.59, -2.826, 16.868]}
      />
      <mesh
        geometry={nodes.visual_bonus_03.geometry}
        material={materials.chrome}
        position={[-9.594, -2.826, 16.868]}
      />
      <group position={[10.362, -2.304, 16.425]}>
        <mesh
          geometry={nodes.posts_outlane_LOD0.geometry}
          material={materials["rubber.001"]}
        />
        <mesh
          geometry={nodes.posts_outlane_LOD0_1.geometry}
          material={materials["chrome.001"]}
        />
      </group>
      <mesh
        geometry={nodes.visual_playfield.geometry}
        material={materials.playfield}
        position={[-0.609, -2.903, 7.762]}
      />
      <mesh
        geometry={nodes.visual_diverter_left_orbit_1.geometry}
        material={materials.metal_sidewalls}
        position={[-12.961, -4.26, -6.792]}
      />
      <mesh
        geometry={nodes.visual_pf_door_right.geometry}
        material={materials.playfield}
        position={[0.327, -2.949, 12.894]}
      />
      <mesh
        geometry={nodes.visual_pf_door_left.geometry}
        material={materials.playfield}
        position={[-2.544, -2.949, 12.894]}
      />
      <mesh
        geometry={nodes.visual_under_pf.geometry}
        material={materials.M_underplayfield}
        position={[-1.109, -4.027, 12.894]}
      />
      <mesh
        geometry={nodes.visual_anu_card_01_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[7.42, -4.603, 7.283]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
      />
      <mesh
        geometry={nodes.visual_anu_card_02_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[7.227, -4.603, 7.663]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
      />
      <mesh
        geometry={nodes.visual_anu_card_03_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[7.037, -4.603, 8.035]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
      />
      <mesh
        geometry={nodes.visual_anu_card_04_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[6.85, -4.603, 8.401]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
      />
      <mesh
        geometry={nodes.visual_anu_card_05_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[6.668, -4.603, 8.76]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
      />
      <mesh
        geometry={nodes.visual_lg_army_of_anubis_02.geometry}
        material={materials.M_anubis_head_eyes}
        position={[6.845, -2.903, -0.448]}
        rotation={[0, 1.286, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.visual_plunger.geometry}
        material={materials.collision}
        position={[12.739, -2.257, 34.931]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.visual_diverter_right_orbit.geometry}
        material={materials.metal_sidewalls}
        position={[12.127, -4.26, -5.269]}
      />
      <mesh
        geometry={nodes.visual_diverter_center03.geometry}
        material={materials.metal_sidewalls}
        position={[2.071, -3.619, -9.05]}
      />
      <mesh
        geometry={nodes.visual_diverter_center01.geometry}
        material={materials.metal_sidewalls}
        position={[1.069, -3.619, -8.599]}
      />
      <mesh
        geometry={nodes.visual_diverter_center02_21.geometry}
        material={materials.metal_sidewalls}
        position={[1.86, -3.828, -8.793]}
      />

      {/* Colliders Fixed */}

      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes.coll_blunt_rubber.geometry}
          position={[0.825, 0.794, -4.6]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_anubis_mouth.geometry}
          position={[6.286, -2.165, 1.131]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_miniplayfield.geometry}
          position={[-1.256, 3.151, -16.458]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_bridge_part_01.geometry}
          position={[-0.02, 3.123, -14.224]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_bridge_part_02.geometry}
          position={[1.061, 3.123, -14.326]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_bridge_part_03.geometry}
          position={[2.142, 3.123, -14.274]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_bridge_part_04.geometry}
          position={[3.224, 3.123, -14.043]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_diverter_to_vuk.geometry}
          position={[12.743, -1.467, -11.82]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_gate.geometry}
          position={[8.733, -1.018, 5.992]}
          rotation={[Math.PI / 2, 0, -1.204]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_safe_pyramid.geometry}
          position={[-4.561, 0.128, -7.912]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_pyramid.geometry}
          position={[-4.314, -2.903, -6.725]}
          rotation={[0, 0.175, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_pyramid_temporary.geometry}
          position={[-4.313, -1.931, -6.723]}
          rotation={[0, 0.175, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_pyramid_wall_03.geometry}
          position={[-4.744, -2.903, -9.162]}
          rotation={[0, 0.175, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_pyramid_door.geometry}
          position={[-4.314, -2.903, -6.725]}
          rotation={[0, 0.175, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_spinner_10.geometry}
          position={[-11.326, -1.294, -1.815]}
          rotation={[Math.PI / 2, 0, 2.827]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_scoops.geometry}
          position={[-5.54, -4.959, -2.812]}
          rotation={[0, 0.579, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_anubis_head_hole.geometry}
          position={[6.633, -2.89, 0.111]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_mpf_metal_wires.geometry}
          position={[1.646, 3.627, -14.449]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        {/* <mesh */}
        {/*   geometry={nodes.coll_mpf_metal_wires.geometry} */}
        {/*   material={materials.collision} */}
        {/*   position={[1.646, 3.627, -14.449]} */}
        {/* /> */}
        <mesh
          geometry={nodes.coll_metal.geometry}
          position={[0.313, -2.424, 23.779]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_rubber.geometry}
          position={[-2.097, -0.236, -1.55]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_super_rubber.geometry}
          position={[-2.105, 0.799, 0.974]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        {/* <mesh */}
        {/*   geometry={nodes.coll_super_rubber.geometry} */}
        {/*   material={materials.collision} */}
        {/*   position={[-2.105, 0.799, 0.974]} */}
        {/* /> */}
        <mesh
          geometry={nodes.coll_ramp_metal.geometry}
          position={[-1.088, -2.185, 21.588]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_sidewalls.geometry}
          position={[-0.557, -2.233, 8.325]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_ramp_left.geometry}
          position={[-8.793, -1.946, -6.392]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_ramp_right.geometry}
          position={[-3.473, -2.903, -8.221]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_playfield_collision.geometry}
          position={[-0.609, -2.903, 7.762]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <group position={[-0.984, -6.695, 10.256]}>
          <mesh geometry={nodes.holes_nocoll_LOD0.geometry}>
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>
          <mesh geometry={nodes.holes_nocoll_LOD0_1.geometry}>
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>
        </group>
        <mesh
          geometry={nodes.coll_locker_door_2001.geometry}
          position={[-0.609, -2.903, 5.131]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_habit_left.geometry}
          position={[-0.609, -2.903, 5.131]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_habit_mini_pf.geometry}
          position={[9.359, 2.86, -6.098]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_habit_right.geometry}
          position={[7.445, -0.413, 8.673]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_ramp_back.geometry}
          position={[-0.575, 0.799, -15.713]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_top.geometry}
          position={[11.053, 4.57, -13.588]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_standard_collision.geometry}
          position={[-0.633, -1.467, 7.78]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_habit_vuk.geometry}
          position={[12.743, -1.395, -19.669]}
          rotation={[0, 0.048, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_sphinx_bottom.geometry}
          position={[-7.292, 3.151, -17.887]}
          rotation={[0, 0.419, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_locker.geometry}
          position={[6.708, 5.391, -17.79]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_ramp_back001.geometry}
          position={[-0.609, -2.903, 5.131]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_bumper01.geometry}
          position={[0.322, 1.563, -16.155]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_bumper02.geometry}
          position={[5.621, 1.563, -15.029]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_bumper03.geometry}
          position={[-0.642, 1.563, -11.62]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_bumper04.geometry}
          position={[4.657, 1.563, -10.494]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_mpf_spindisk_wall.geometry}
          position={[-5.499, 3.627, -15.866]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_droptarget_mpf_01.geometry}
          position={[-8.61, 2.886, -14.238]}
          rotation={[0, Math.PI / 6, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_droptarget_mpf_02.geometry}
          position={[-8.751, 2.886, -14.482]}
          rotation={[0, Math.PI / 6, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_droptarget_mpf_03.geometry}
          position={[-8.892, 2.886, -14.727]}
          rotation={[0, Math.PI / 6, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_droptarget_mpf_04.geometry}
          position={[-9.034, 2.886, -14.972]}
          rotation={[0, Math.PI / 6, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_droptarget_mpf_05.geometry}
          position={[-9.175, 2.886, -15.217]}
          rotation={[0, Math.PI / 6, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_target.geometry}
          position={[9.56, 3.827, -15.206]}
          rotation={[Math.PI / 2, 0, 0.244]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_target001.geometry}
          position={[11.756, 3.827, -13.071]}
          rotation={[Math.PI / 2, 0, 1.1]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_spindisk_mpf.geometry}
          position={[-2.597, 3.151, -17.494]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_locker_launch.geometry}
          position={[6.717, 5.166, -17.626]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_scoops01_6.geometry}
          position={[-1.947, 1.029, -23.697]}
          rotation={[0, 0.517, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_gate_mpf_left.geometry}
          position={[-1.267, 5.006, -21.296]}
          rotation={[Math.PI / 2, 0, 1.466]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_gate_mpf_right_2.geometry}
          position={[6.037, 5.006, -21.217]}
          rotation={[Math.PI / 2, 0, -1.431]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_diverter_right_orbit.geometry}
          position={[11.811, -3.59, -5.28]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_diverter_center02_20.geometry}
          position={[1.86, -3.828, -8.793]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_diverter_center03.geometry}
          position={[2.071, -3.619, -9.05]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_diverter_center01.geometry}
          position={[1.069, -3.619, -8.599]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_diverter_plunger_back.geometry}
          position={[12.732, -2.233, -5.807]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_diverter_plunger.geometry}
          position={[7.347, -5.606, 12.008]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
      </RigidBody>
      <RigidBody type="fixed" position={[-11, 1, 2]}>
        {/* Mesh rectangle simple */}
        <mesh position={[-0.609, -2.903, 5.131]}>
          <boxGeometry args={[1, 1, 0.2]} />
          <meshBasicMaterial color="red" />
        </mesh>

        {/* Collider rectangle */}
        <CuboidCollider
          args={[1.5, 1, 0.1]} // demi-tailles
          position={[-0.609, -2.903, 5.131]}
          rotation={[0, 0.65, 0]} // ← 25° sur Z
        />
      </RigidBody>
      {/* Flippers */}
      {/* --- FLIPPERS GAUCHES --- */}
      <Flipper
        side="left"
        position={[-5.001, -2.903, 26.34]}
        rotation={[0, -Math.PI / 6, 0]}
        colliderGeometry={nodes.coll_flipper_left_bottom.geometry}
        visualGeometry={nodes.visual_obj_flipper_left_bottom.geometry}
        visualMaterial={materials.M_flipper_arm_left}
      />
      <Flipper
        side="left"
        position={[-8.676, 3.161, -11.209]}
        rotation={[0, -0.855, 0]}
        colliderGeometry={nodes.coll_flipper_mini_left.geometry}
        visualGeometry={nodes.visual_obj_flipper_mini_left.geometry}
        visualMaterial={materials.M_flipper_mini_arm_left}
      />
      <Flipper
        side="left"
        position={[5.722, 3.161, -11.44]}
        rotation={[0, -1.012, 0]}
        colliderGeometry={nodes.coll_flipper_mini_left001.geometry}
        visualGeometry={nodes.visual_obj_flipper_mini_left001.geometry}
        visualMaterial={materials.M_flipper_mini_arm_left2}
      />

      {/* --- FLIPPERS DROITS --- */}
      <Flipper
        side="right"
        position={[2.787, -2.903, 26.34]}
        rotation={[0, Math.PI / 6, -Math.PI]}
        colliderGeometry={nodes.coll_flipper_right_bottom.geometry}
        visualGeometry={nodes.visual_obj_flipper_right_bottom.geometry}
        visualMaterial={materials.M_flipper_arm_right}
      />
      <Flipper
        side="right"
        position={[-0.886, 3.161, -11.668]}
        rotation={[0, 0.96, Math.PI]}
        colliderGeometry={nodes.coll_flipper_mini_right.geometry}
        visualGeometry={nodes.visual_obj_flipper_mini_right.geometry}
        visualMaterial={materials.M_flipper_mini_arm_right}
      />
      <Flipper
        side="right"
        position={[11.746, 3.161, -10.092]}
        rotation={[0, 0.367, Math.PI]}
        colliderGeometry={nodes.coll_flipper_mini_right001.geometry}
        visualGeometry={nodes.visual_obj_flipper_mini_right001.geometry}
        visualMaterial={materials.M_flipper_mini_arm_right2}
      />
      {/* <RigidBody type="fixed" colliders="trimesh"> */}

      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_mini_left.geometry} */}
      {/*   material={materials.M_flipper_mini_arm_left} */}
      {/*   position={[-8.676, 3.161, -11.209]} */}
      {/*   rotation={[0, -0.855, 0]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_mini_left001.geometry} */}
      {/*   material={materials.M_flipper_mini_arm_left2} */}
      {/*   position={[5.722, 3.161, -11.44]} */}
      {/*   rotation={[0, -1.012, 0]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_mini_right.geometry} */}
      {/*   material={materials.M_flipper_mini_arm_right} */}
      {/*   position={[-0.886, 3.161, -11.668]} */}
      {/*   rotation={[0, 0.96, Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_mini_right001.geometry} */}
      {/*   material={materials.M_flipper_mini_arm_right2} */}
      {/*   position={[11.746, 3.161, -10.092]} */}
      {/*   rotation={[0, 0.367, Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_left_bottom.geometry} */}
      {/*   material={materials.M_flipper_arm_left} */}
      {/*   position={[-5.001, -2.903, 26.34]} */}
      {/*   rotation={[0, -Math.PI / 6, 0]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.visual_obj_flipper_right_bottom.geometry} */}
      {/*   material={materials.M_flipper_arm_right} */}
      {/*   position={[2.787, -2.903, 26.34]} */}
      {/*   rotation={[0, Math.PI / 6, -Math.PI]} */}
      {/* /> */}
      {/*   <mesh */}
      {/*     geometry={nodes.coll_flipper_left_bottom.geometry} */}
      {/*     position={[-5.001, -2.903, 26.34]} */}
      {/*     rotation={[0, -Math.PI / 6, 0]} */}
      {/*   > */}
      {/*     <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
      {/*   </mesh> */}
      {/**/}
      {/*   <mesh */}
      {/*     geometry={nodes.coll_flipper_right_bottom.geometry} */}
      {/*     position={[2.787, -2.903, 26.34]} */}
      {/*     rotation={[0, Math.PI / 6, -Math.PI]} */}
      {/*   > */}
      {/*     <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
      {/*   </mesh> */}
      {/**/}
      {/*   <mesh */}
      {/*     geometry={nodes.coll_flipper_mini_left.geometry} */}
      {/*     position={[-8.676, 3.161, -11.209]} */}
      {/*     rotation={[0, -0.855, 0]} */}
      {/*   > */}
      {/*     <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
      {/*   </mesh> */}
      {/*   <mesh */}
      {/*     geometry={nodes.coll_flipper_mini_left001.geometry} */}
      {/*     position={[5.722, 3.161, -11.44]} */}
      {/*     rotation={[0, -1.012, 0]} */}
      {/*   > */}
      {/*     <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
      {/*   </mesh> */}
      {/**/}
      {/*   <mesh */}
      {/*     geometry={nodes.coll_flipper_mini_right.geometry} */}
      {/*     position={[-0.886, 3.161, -11.668]} */}
      {/*     rotation={[0, 0.96, Math.PI]} */}
      {/*   > */}
      {/*     <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
      {/*   </mesh> */}
      {/**/}
      {/*   <mesh */}
      {/*     geometry={nodes.coll_flipper_mini_right001.geometry} */}
      {/*     position={[11.746, 3.161, -10.092]} */}
      {/*     rotation={[0, 0.367, Math.PI]} */}
      {/*   > */}
      {/*     <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
      {/*   </mesh> */}
      {/* </RigidBody> */}
      {/**/}
      <mesh
        geometry={nodes.coll_nile.geometry}
        material={materials.collision}
        position={[2.49, 1.085, -13.324]}
        rotation={[0, -0.209, 0]}
      />
      <mesh
        geometry={nodes.coll_mpf_spinner.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-2.597, 3.151, -17.494]}
        rotation={[0, -1.309, Math.PI / 2]}
      />

      <mesh
        geometry={nodes.coll_fr_slingshot_flasher_left.geometry}
        material={materials.M_slingshot_flasher_emissive}
        position={[-7.408, -1.169, 18.044]}
      />
      <mesh
        geometry={nodes.coll_fr_slingshot_flasher_right.geometry}
        material={materials.M_slingshot_flasher_emissive}
        position={[5.178, -1.169, 18.044]}
      />

      <mesh
        geometry={nodes.coll_left_kickback_door.geometry}
        material={materials.metal_sidewalls}
        position={[-13.574, -2.233, 23.626]}
      />

      <mesh
        geometry={nodes.coll_posts_outlane.geometry}
        material={materials.collision}
        position={[-2.08, -2.233, 16.425]}
      />

      <mesh
        geometry={nodes.coll_left_hole.geometry}
        material={materials.collision}
        position={[-12.556, -5.859, 5.794]}
      />
      <mesh
        geometry={nodes.coll_diverter_left_orbit_0.geometry}
        material={materials.collision}
        position={[-12.961, -4.26, -6.792]}
      />
      {/* <mesh */}
      {/*   geometry={nodes.coll_under_pf.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[-1.109, -4.027, 12.894]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_anu_card_01.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[7.42, -4.603, 7.283]} */}
      {/*   rotation={[-Math.PI, 0.054, -Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_anu_card_02.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[7.227, -4.603, 7.663]} */}
      {/*   rotation={[-Math.PI, 0.054, -Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_anu_card_03.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[7.037, -4.603, 8.035]} */}
      {/*   rotation={[-Math.PI, 0.068, -Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_anu_card_04.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[6.85, -4.603, 8.401]} */}
      {/*   rotation={[-Math.PI, 0.061, -Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_anu_card_05.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[6.668, -4.603, 8.76]} */}
      {/*   rotation={[-Math.PI, 0.054, -Math.PI]} */}
      {/* /> */}
      {/* --- SLINGSHOTS --- */}
      {/* --- SLINGSHOTS BAS --- */}
      {/* Le gauche renvoie la bille vers la droite (+X) et vers le haut (-Z) */}
      <Slingshot
        geometry={nodes.coll_left_sling_collision_bottom.geometry}
        position={[-5.786, -2.233, 21.888]}
        rotation={[Math.PI / 2, 0, -1.92]}
        pushDirection={[1, 0, -1]}
      />

      {/* Le droit renvoie la bille vers la gauche (-X) et vers le haut (-Z) */}
      <Slingshot
        geometry={nodes.coll_right_sling_collision_bottom.geometry}
        position={[3.57, -2.185, 21.888]}
        rotation={[-Math.PI / 2, 0, 1.222]}
        pushDirection={[-1, 0, -1]}
      />

      {/* --- SLINGSHOTS HAUT --- */}
      {/* À ajuster selon l'orientation de tes slingshots du haut ! */}
      <Slingshot
        geometry={nodes.coll_left_sling_collision_top.geometry}
        position={[-7.708, -2.233, 16.596]}
        rotation={[-Math.PI / 2, 0, -1.222]}
        pushDirection={[1, 0, 0]} // Pousse purement vers la droite
      />

      <Slingshot
        geometry={nodes.coll_right_sling_collision_top.geometry}
        position={[5.493, -2.185, 16.596]}
        rotation={[Math.PI / 2, 0, 1.92]}
        pushDirection={[-1, 0, 0]} // Pousse purement vers la gauche
      />
      {/* <mesh */}
      {/*   geometry={nodes.coll_right_sling_collision_bottom.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[3.57, -2.185, 21.888]} */}
      {/*   rotation={[-Math.PI / 2, 0, 1.222]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_left_sling_collision_bottom.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[-5.786, -2.233, 21.888]} */}
      {/*   rotation={[Math.PI / 2, 0, -1.92]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_left_sling_collision_top.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[-7.708, -2.233, 16.596]} */}
      {/*   rotation={[-Math.PI / 2, 0, -1.222]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.coll_right_sling_collision_top.geometry} */}
      {/*   material={materials.collision} */}
      {/*   position={[5.493, -2.185, 16.596]} */}
      {/*   rotation={[Math.PI / 2, 0, 1.92]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_mpf_presence_0.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[2.318, 3.978, -14.809]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_mini_left001_arm.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[5.722, 3.161, -11.44]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_mini_left_arm.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-8.676, 3.161, -11.209]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_mini_right001_arm.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[11.746, 3.161, -10.092]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_mini_right_arm.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-0.886, 3.161, -11.668]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_nile.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[2.639, 1.55, -13.563]} */}
      {/*   rotation={[0, -0.209, 0]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_bridge_left.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-0.901, 4.005, -14.058]} */}
      {/*   rotation={[0, 0.055, -Math.PI / 2]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_bridge_right.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[5.219, 4.005, -13.41]} */}
      {/*   rotation={[0, 0.053, Math.PI / 2]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_bridge.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[2.233, 3.423, -13.612]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_left_bottom_arm.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-4.996, -2.903, 26.331]} */}
      {/*   rotation={[0, -Math.PI / 6, 0]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_right_bottom_arm.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[2.782, -2.903, 26.331]} */}
      {/*   rotation={[0, Math.PI / 6, -Math.PI]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.stick_barrier.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-1.863, -2.257, 23.62]} */}
      {/*   rotation={[0, -1.571, 0]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.TrialHoleDrainSensor.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-1.075, -2.257, 32.198]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.launched.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[11.421, -2.257, 12.87]} */}
      {/* /> */}
      {/* <mesh */}
      {/*   geometry={nodes.sensor_sinkhole_left.geometry} */}
      {/*   material={materials.sensors} */}
      {/*   position={[-12.846, -7.494, 5.356]} */}
      {/*   rotation={[0, 0.593, Math.PI / 2]} */}
      {/* /> */}
      <mesh
        geometry={nodes.visual_crocodile_plunger.geometry}
        material={materials.M_crocodile_plunger}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_anubis.geometry}
        material={materials.M_anubis_head}
        position={[6.514, -1.016, 0.293]}
        rotation={[0, -0.029, 0]}
      />
      <mesh
        geometry={nodes.visual_ornate_torch_04_20.geometry}
        material={materials.M_Torches}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_locker_door_2.geometry}
        material={materials.M_locker}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_sarcophagus01_door_3001.geometry}
        material={materials.M_sarcophagus}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_anubis_under_pf_11001.geometry}
        material={materials.M_anubis_head_mpf}
        position={[-6.079, -5.074, 9.784]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        geometry={nodes.visual_anubis_under_pf2001.geometry}
        material={materials.M_anubis_head_mpf}
        position={[3.824, -5.256, 16.004]}
        rotation={[-1.568, -1.568, -1.568]}
      />
      <mesh
        geometry={nodes.visual_torch_left_24001.geometry}
        material={materials.M_Torches}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_torch_right_28001.geometry}
        material={materials.M_Torches}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_ornate_torch_01_14001.geometry}
        material={materials.M_Torches}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_ornate_torch_03_17.geometry}
        material={materials.M_Torches}
        position={[-0.609, -2.903, 5.131]}
      />
      <mesh
        geometry={nodes.visual_crochead1001.geometry}
        material={materials.M_crocodile_plunger}
        position={[-0.439, 1.569, -16.852]}
        rotation={[Math.PI, -0.806, Math.PI]}
      />
      <mesh
        geometry={nodes.visual_crochead2_19001.geometry}
        material={materials.M_crocodile_plunger}
        position={[6.633, 1.569, -15.194]}
        rotation={[-Math.PI, 1.394, -Math.PI]}
      />
      <mesh
        geometry={nodes.visual_crochead3001.geometry}
        material={materials.M_crocodile_plunger}
        position={[-1.628, 1.569, -11.303]}
        rotation={[0, -1.312, 0]}
      />
      <mesh
        geometry={nodes.visual_crochead4_18001.geometry}
        material={materials.M_crocodile_plunger}
        position={[5.465, 1.569, -9.733]}
        rotation={[0, 0.806, 0]}
      />
      <mesh
        geometry={nodes.visual_slingshot_left_10001.geometry}
        material={materials.rubber}
        position={[-6.883, -2.257, 19.289]}
      />
      <mesh
        geometry={nodes.visual_slingshot_right_7001.geometry}
        material={materials.rubber}
        position={[4.933, -2.257, 19.383]}
      />
      <mesh
        geometry={nodes.visual_waterlvl_bubble_2001.geometry}
        material={materials.water_level_bubble}
        position={[-0.896, -2.984, 5.131]}
      />
    </group>
  );
}

useGLTF.preload("/models/PinballMVP_Resized.glb");
