/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PinballMVP_Base.glb -T -t -j -o src/components/models/PinballMVP_Base.tsx 
Files: public/models/PinballMVP_Base.glb [44.5MB] > /Users/adrienallard/Développement/HETIC/Pinball_ThreeJs/frontend/src/components/models/PinballMVP_Base-transformed.glb [3.36MB] (92%)
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import type { JSX } from "react";
import { RigidBody } from "@react-three/rapier";
import Flipper from "@/components/Flipper";
import Slingshot from "@/components/Slingshot";

type GLTFResult = GLTF & {
  nodes: {
    visual_lg_10x: THREE.Mesh;
    visual_lg_2x: THREE.Mesh;
    visual_lg_3x: THREE.Mesh;
    visual_lg_4x: THREE.Mesh;
    visual_lg_5x: THREE.Mesh;
    visual_lg_6x: THREE.Mesh;
    visual_lg_7x: THREE.Mesh;
    visual_lg_8x: THREE.Mesh;
    visual_lg_9x: THREE.Mesh;
    screws_LOD0: THREE.Mesh;
    screws_LOD0_1: THREE.Mesh;
    visual_obj_flipper_left_bottom: THREE.Mesh;
    visual_obj_flipper_right_bottom: THREE.Mesh;
    visual_obj_gate_5: THREE.Mesh;
    visual_sidewalls: THREE.Mesh;
    visual_right_kickback_door: THREE.Mesh;
    holes_nocoll_LOD0: THREE.Mesh;
    holes_nocoll_LOD0_1: THREE.Mesh;
    visual_ball_rollover: THREE.Mesh;
    visual_bonus_05: THREE.Mesh;
    visual_bonus_01: THREE.Mesh;
    visual_bonus_02: THREE.Mesh;
    visual_bonus_03: THREE.Mesh;
    visual_bonus_04: THREE.Mesh;
    posts_outlane_LOD0: THREE.Mesh;
    posts_outlane_LOD0_1: THREE.Mesh;
    visual_plunger: THREE.Mesh;
    visual_left_hole_ramp: THREE.Mesh;
    visual_left_kickback_door: THREE.Mesh;
    visual_playfield_left_hole: THREE.Mesh;
    visual_holding_flag: THREE.Mesh;
    visual_screws_slingshots: THREE.Mesh;
    visual_super_rubber: THREE.Mesh;
    visual_screws_13002: THREE.Mesh;
    visual_overlap_left_wall: THREE.Mesh;
    visual_sidewalls001: THREE.Mesh;
    visual_overlap_bottom_3002: THREE.Mesh;
    visual_standard: THREE.Mesh;
    visual_sidewalls002: THREE.Mesh;
    visual_ramp_back_test001: THREE.Mesh;
    visual_standard_collision_sidewalls_back001: THREE.Mesh;
    visual_habit_right_9_top: THREE.Mesh;
    visual_habit_right_left_9_top002: THREE.Mesh;
    visual_barrel_bumpers: THREE.Mesh;
    coll_flipper_left_bottom: THREE.Mesh;
    coll_flipper_right_bottom: THREE.Mesh;
    coll_gate: THREE.Mesh;
    coll_metal: THREE.Mesh;
    coll_ramp_metal: THREE.Mesh;
    coll_sidewalls: THREE.Mesh;
    coll_left_kickback_door: THREE.Mesh;
    coll_diverter_plunger: THREE.Mesh;
    coll_posts_outlane: THREE.Mesh;
    coll_left_hole: THREE.Mesh;
    coll_right_sling_collision_bottom: THREE.Mesh;
    coll_left_sling_collision_bottom: THREE.Mesh;
    coll_left_sling_collision_top: THREE.Mesh;
    coll_right_sling_collision_top: THREE.Mesh;
    coll_super_rubber: THREE.Mesh;
    coll_standard_collision: THREE.Mesh;
    coll_rubber: THREE.Mesh;
    coll_standard_collision_sidewalls_back: THREE.Mesh;
    coll_playfield_collision_left_hole: THREE.Mesh;
    coll_ramp_back_test: THREE.Mesh;
    coll_scoop_hole_left: THREE.Mesh;
    habit_right_LOD0007: THREE.Mesh;
    habit_right_LOD0007_1: THREE.Mesh;
    coll_right_9_top001: THREE.Mesh;
    coll_bumpers: THREE.Mesh;
    Tower_Brick_MT_0: THREE.Mesh;
    Tower_Details_MT_0: THREE.Mesh;
    Tower_Glass_MT_0: THREE.Mesh;
    Tower_Plaster_MT_0: THREE.Mesh;
    Tower_Roof_MT_0: THREE.Mesh;
  };
  materials: {
    lamp_playfield: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    M_flipper_arm_left: THREE.MeshStandardMaterial;
    M_flipper_arm_right: THREE.MeshStandardMaterial;
    ["metal_sidewalls.001"]: THREE.MeshStandardMaterial;
    ["M_playfield_cutout.001"]: THREE.MeshStandardMaterial;
    M_black: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    rubber: THREE.MeshStandardMaterial;
    playfield: THREE.MeshStandardMaterial;
    Brick2: THREE.MeshStandardMaterial;
    ["barrel.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    Brick_MT: THREE.MeshStandardMaterial;
    Details_MT: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshPhysicalMaterial;
    Plaster_MT: THREE.MeshStandardMaterial;
    Roof_MT: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export default function PinballMVPBase(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/PinballMVP_Base2-transformed.glb",
  ) as unknown as GLTFResult;

  return (
    <>
      <Slingshot
        geometry={nodes.coll_left_sling_collision_bottom.geometry}
        position={[-5.786, -2.233, 21.888]}
        rotation={[Math.PI / 2, 0, -1.92]}
        pushDirection={[1, 0, -1]}
      />

      {/* Le droit renvoie la bille vers la gauche (-X) et vers le haut (-Z) */}
      <Slingshot
        geometry={nodes.coll_right_sling_collision_bottom.geometry}
        position={[3.57, -2.185, 21.888]}
        rotation={[-Math.PI / 2, 0, 1.222]}
        pushDirection={[-1, 0, -1]}
      />

      {/* Flippers */}
      {/* --- FLIPPERS GAUCHES --- */}
      <Flipper
        side="left"
        position={[-5.001, -2.903, 26.34]}
        rotation={[0, -Math.PI / 6, 0]}
        colliderGeometry={nodes.coll_flipper_left_bottom.geometry}
        visualGeometry={nodes.visual_obj_flipper_left_bottom.geometry}
        visualMaterial={materials.M_flipper_arm_left}
      />

      {/* --- FLIPPERS DROITS --- */}
      <Flipper
        side="right"
        position={[2.787, -2.903, 26.34]}
        rotation={[0, Math.PI / 6, -Math.PI]}
        colliderGeometry={nodes.coll_flipper_right_bottom.geometry}
        visualGeometry={nodes.visual_obj_flipper_right_bottom.geometry}
        visualMaterial={materials.M_flipper_arm_right}
      />
      {/* Colliders Fixed */}
      <RigidBody type="fixed" colliders="trimesh">
        <group position={[0.143, -4.465, -2.19]} rotation={[0, 0.08, 0]}>
          <mesh geometry={nodes.habit_right_LOD0007.geometry}>
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>
          <mesh geometry={nodes.habit_right_LOD0007_1.geometry}>
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>
        </group>

        <group position={[-0.984, -6.695, 10.256]}>
          <mesh geometry={nodes.holes_nocoll_LOD0.geometry}>
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>

          <mesh geometry={nodes.holes_nocoll_LOD0_1.geometry}>
            <meshBasicMaterial transparent opacity={0} depthWrite={false} />
          </mesh>
        </group>
        <mesh
          geometry={nodes.coll_right_9_top001.geometry}
          position={[0.143, -4.465, -2.19]}
          rotation={[0, 0.08, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_bumpers.geometry}
          position={[-4.744, -2.898, -6.463]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        {/* <mesh */}
        {/*   geometry={nodes.coll_flipper_left_bottom.geometry} */}
        {/*   position={[-5.001, -2.903, 26.34]} */}
        {/*   rotation={[0, -Math.PI / 6, 0]} */}
        {/* > */}
        {/*   <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
        {/* </mesh> */}
        {/* <mesh */}
        {/*   geometry={nodes.coll_flipper_right_bottom.geometry} */}
        {/*   material={materials.PaletteMaterial003} */}
        {/*   position={[2.787, -2.903, 26.34]} */}
        {/*   rotation={[0, Math.PI / 6, -Math.PI]} */}
        {/* > */}
        {/*   <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
        {/* </mesh> */}
        <mesh
          geometry={nodes.coll_gate.geometry}
          position={[8.733, -1.272, 5.992]}
          rotation={[Math.PI / 2, 0, -1.204]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_metal.geometry}
          position={[0.313, -2.424, 23.779]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_ramp_metal.geometry}
          position={[-1.088, -2.185, 21.588]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_sidewalls.geometry}
          position={[-0.557, -2.233, 8.325]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_left_kickback_door.geometry}
          position={[-13.574, -2.233, 23.626]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_diverter_plunger.geometry}
          position={[7.347, -5.606, 12.008]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>

        <mesh
          geometry={nodes.coll_posts_outlane.geometry}
          position={[-2.08, -2.233, 16.425]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_left_hole.geometry}
          position={[-12.556, -5.859, 5.794]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        {/* <mesh */}
        {/*   geometry={nodes.coll_right_sling_collision_bottom.geometry} */}
        {/*   position={[3.57, -2.185, 21.888]} */}
        {/*   rotation={[-Math.PI / 2, 0, 1.222]} */}
        {/* > */}
        {/*   <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
        {/* </mesh> */}
        {/* <mesh */}
        {/*   geometry={nodes.coll_left_sling_collision_bottom.geometry} */}
        {/*   position={[-5.786, -2.233, 21.888]} */}
        {/*   rotation={[Math.PI / 2, 0, -1.92]} */}
        {/* > */}
        {/*   <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
        {/* </mesh> */}
        {/* <mesh */}
        {/*   geometry={nodes.coll_left_sling_collision_top.geometry} */}
        {/*   position={[-7.708, -2.233, 16.596]} */}
        {/*   rotation={[-Math.PI / 2, 0, -1.222]} */}
        {/* > */}
        {/*   <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
        {/* </mesh> */}
        {/* <mesh */}
        {/*   geometry={nodes.coll_right_sling_collision_top.geometry} */}
        {/*   position={[5.493, -2.185, 16.596]} */}
        {/*   rotation={[Math.PI / 2, 0, 1.92]} */}
        {/* > */}
        {/*   <meshBasicMaterial transparent opacity={0} depthWrite={false} /> */}
        {/* </mesh> */}
        <mesh
          geometry={nodes.coll_super_rubber.geometry}
          position={[-2.105, 0.799, 0.974]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_standard_collision.geometry}
          position={[-0.633, -1.467, 7.78]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_rubber.geometry}
          position={[-2.097, -0.236, -1.55]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_standard_collision_sidewalls_back.geometry}
          position={[-0.633, -10.856, 7.78]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_playfield_collision_left_hole.geometry}
          position={[-0.609, -2.903, 7.762]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_ramp_back_test.geometry}
          position={[-0.609, -2.903, 5.131]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
        <mesh
          geometry={nodes.coll_scoop_hole_left.geometry}
          position={[-5.54, -4.959, -2.812]}
          rotation={[0, 0.579, 0]}
        >
          <meshBasicMaterial transparent opacity={0} depthWrite={false} />
        </mesh>
      </RigidBody>

      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.visual_lg_10x.geometry}
          material={materials.lamp_playfield}
          position={[9.292, -1.596, 25.651]}
        />
        <mesh
          geometry={nodes.visual_lg_2x.geometry}
          material={materials.lamp_playfield}
          position={[0.924, -1.551, 30.58]}
        />
        <mesh
          geometry={nodes.visual_lg_3x.geometry}
          material={materials.lamp_playfield}
          position={[1.992, -1.527, 30.17]}
        />
        <mesh
          geometry={nodes.visual_lg_4x.geometry}
          material={materials.lamp_playfield}
          position={[3.144, -1.526, 29.57]}
        />
        <mesh
          geometry={nodes.visual_lg_5x.geometry}
          material={materials.lamp_playfield}
          position={[4.085, -1.568, 28.91]}
        />
        <mesh
          geometry={nodes.visual_lg_6x.geometry}
          material={materials.lamp_playfield}
          position={[5.183, -1.574, 28.271]}
        />
        <mesh
          geometry={nodes.visual_lg_7x.geometry}
          material={materials.lamp_playfield}
          position={[6.097, -1.556, 27.7]}
        />
        <mesh
          geometry={nodes.visual_lg_8x.geometry}
          material={materials.lamp_playfield}
          position={[7.2, -1.533, 27.003]}
        />
        <mesh
          geometry={nodes.visual_lg_9x.geometry}
          material={materials.lamp_playfield}
          position={[8.219, -1.54, 26.367]}
        />
        <group position={[-0.609, -2.903, 5.131]}>
          <mesh
            geometry={nodes.screws_LOD0.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            geometry={nodes.screws_LOD0_1.geometry}
            material={materials.rubber}
          />
        </group>
        {/* <mesh */}
        {/*   geometry={nodes.visual_obj_flipper_left_bottom.geometry} */}
        {/*   material={materials.M_flipper_arm_left} */}
        {/*   position={[-5.001, -2.903, 26.34]} */}
        {/*   rotation={[0, -Math.PI / 6, 0]} */}
        {/* /> */}
        {/* <mesh */}
        {/*   geometry={nodes.visual_obj_flipper_right_bottom.geometry} */}
        {/*   material={materials.M_flipper_arm_right} */}
        {/*   position={[2.787, -2.903, 26.34]} */}
        {/*   rotation={[0, Math.PI / 6, -Math.PI]} */}
        {/* /> */}
        <mesh
          geometry={nodes.visual_obj_gate_5.geometry}
          material={materials.PaletteMaterial001}
          position={[8.733, -1.018, 5.992]}
          rotation={[Math.PI / 2, 0, -1.204]}
        />
        <mesh
          geometry={nodes.visual_sidewalls.geometry}
          material={materials.M_black}
          position={[-0.609, -2.903, 5.131]}
        />
        <mesh
          geometry={nodes.visual_right_kickback_door.geometry}
          material={materials["metal_sidewalls.001"]}
          position={[8.532, -1.97, 25.481]}
          rotation={[Math.PI, -1.187, Math.PI]}
        />
        <mesh
          geometry={nodes.visual_ball_rollover.geometry}
          material={materials.PaletteMaterial001}
          position={[12.739, -2.83, 28.136]}
        />
        <mesh
          geometry={nodes.visual_bonus_05.geometry}
          material={materials.PaletteMaterial001}
          position={[9.354, -2.826, 16.868]}
        />
        <mesh
          geometry={nodes.visual_bonus_01.geometry}
          material={materials.PaletteMaterial001}
          position={[-13.585, -2.826, 16.868]}
        />
        <mesh
          geometry={nodes.visual_bonus_02.geometry}
          material={materials.PaletteMaterial001}
          position={[-11.59, -2.826, 16.868]}
        />
        <mesh
          geometry={nodes.visual_bonus_03.geometry}
          material={materials.PaletteMaterial001}
          position={[-9.594, -2.826, 16.868]}
        />
        <mesh
          geometry={nodes.visual_bonus_04.geometry}
          material={materials.PaletteMaterial002}
          position={[7.358, -2.826, 16.868]}
        />
        <group position={[10.362, -2.304, 16.425]}>
          <mesh
            geometry={nodes.posts_outlane_LOD0.geometry}
            material={materials.rubber}
          />
          <mesh
            geometry={nodes.posts_outlane_LOD0_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <mesh
          geometry={nodes.visual_plunger.geometry}
          material={materials.PaletteMaterial003}
          position={[12.739, -2.257, 34.931]}
          rotation={[-Math.PI, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.visual_left_hole_ramp.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.609, -2.903, 5.131]}
        />
        <mesh
          geometry={nodes.visual_left_kickback_door.geometry}
          material={materials.M_black}
          position={[-12.665, -1.97, 24.302]}
          rotation={[-Math.PI, 1.187, -Math.PI]}
        />
        <mesh
          geometry={nodes.visual_playfield_left_hole.geometry}
          material={materials.playfield}
          position={[-0.609, -2.903, 7.762]}
        />
        <mesh
          geometry={nodes.visual_holding_flag.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.622, -2.903, 5.131]}
        />
        <mesh
          geometry={nodes.visual_screws_slingshots.geometry}
          material={materials.PaletteMaterial001}
          position={[-1.108, -1.247, 19.416]}
        />
        <mesh
          geometry={nodes.visual_super_rubber.geometry}
          material={materials.PaletteMaterial001}
          position={[-2.105, 0.799, 0.974]}
        />
        <mesh
          geometry={nodes.visual_screws_13002.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.609, 0.4, 5.131]}
        />
        <mesh
          geometry={nodes.visual_overlap_left_wall.geometry}
          material={materials.M_black}
          position={[-0.609, -2.903, 5.131]}
        />
        <mesh
          geometry={nodes.visual_sidewalls001.geometry}
          material={materials.M_black}
          position={[-0.609, -2.903, 5.131]}
        />
        <mesh
          geometry={nodes.visual_overlap_bottom_3002.geometry}
          material={materials.M_black}
          position={[-0.609, -2.377, 5.131]}
        />
        <mesh
          geometry={nodes.visual_standard.geometry}
          material={materials.PaletteMaterial003}
          position={[-0.633, -1.56, 7.78]}
        />
        <mesh
          geometry={nodes.visual_sidewalls002.geometry}
          material={materials.PaletteMaterial003}
          position={[-0.557, -2.233, 8.325]}
        />
        <mesh
          geometry={nodes.visual_ramp_back_test001.geometry}
          material={materials.Brick2}
          position={[-0.609, -2.903, 5.131]}
        />
        <mesh
          geometry={nodes.visual_standard_collision_sidewalls_back001.geometry}
          material={materials.M_black}
          position={[-0.633, -10.856, 7.78]}
        />
        <mesh
          geometry={nodes.visual_habit_right_9_top.geometry}
          material={materials.PaletteMaterial001}
          position={[0.143, -4.465, -2.19]}
          rotation={[0, 0.08, 0]}
        />
        <mesh
          geometry={nodes.visual_habit_right_left_9_top002.geometry}
          material={materials.PaletteMaterial001}
          position={[0.143, -4.465, -2.19]}
          rotation={[0, 0.08, 0]}
        />
        <mesh
          geometry={nodes.visual_barrel_bumpers.geometry}
          material={materials["barrel.001"]}
          position={[-4.745, -2.898, -6.462]}
          rotation={[-1.571, 0, -2.33]}
        />

        <mesh
          geometry={nodes.Tower_Brick_MT_0.geometry}
          material={materials.Brick_MT}
          position={[-13.618, 3.446, 2.318]}
          rotation={[-Math.PI / 2, 0, -1.688]}
        />
        <mesh
          geometry={nodes.Tower_Details_MT_0.geometry}
          material={materials.Details_MT}
          position={[-13.618, 3.446, 2.318]}
          rotation={[-Math.PI / 2, 0, -1.688]}
        />
        <mesh
          geometry={nodes.Tower_Glass_MT_0.geometry}
          material={materials.PaletteMaterial004}
          position={[-13.618, 3.446, 2.318]}
          rotation={[-Math.PI / 2, 0, -1.688]}
        />
        <mesh
          geometry={nodes.Tower_Plaster_MT_0.geometry}
          material={materials.Plaster_MT}
          position={[-13.618, 3.446, 2.318]}
          rotation={[-Math.PI / 2, 0, -1.688]}
        />
        <mesh
          geometry={nodes.Tower_Roof_MT_0.geometry}
          material={materials.Roof_MT}
          position={[-13.618, 3.446, 2.318]}
          rotation={[-Math.PI / 2, 0, -1.688]}
        />
      </group>
    </>
  );
}

useGLTF.preload("/models/PinballMVP_Base2-transformed.glb");
