/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PinballMVP_Maker.glb -T -t -j -o src/components/models/PinballMVP_Maker.tsx
Files: public/models/PinballMVP_Maker.glb [66.4KB] > /home/steph/dev/hetic/Pinball_three.js/frontend/src/components/models/PinballMVP_Maker-transformed.glb [16.01KB] (76%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RigidBody, CuboidCollider } from '@react-three/rapier'
import Flipper from '@/components/pinball/Flipper'
import { useGameStore } from '@/store/gameStore/useGameStore'

type GLTFResult = GLTF & {
  nodes: {
    coll_maker_playfield_collision: THREE.Mesh
    coll_maker_gate: THREE.Mesh
    coll_maker_standard_collision_sidewalls: THREE.Mesh
    coll_maker_flipper_left_bottom: THREE.Mesh
    coll_maker_flipper_right_bottom: THREE.Mesh
    coll_maker_super_rubber: THREE.Mesh
    coll_maker_metal: THREE.Mesh
    coll_maker_slingshot_left: THREE.Mesh
    coll_maker_slingshot_right: THREE.Mesh
    coll_maker_guidance_right: THREE.Mesh
    coll_maker_guidance_left: THREE.Mesh
    coll_maker_glass_panel: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
}

type MeshDef = {
  geometry: THREE.BufferGeometry
  material: THREE.MeshStandardMaterial
  position: [number, number, number]
}

type Props = JSX.IntrinsicElements['group'] & { withPhysics?: boolean }

export function PinballMVPMaker({ withPhysics = false, ...props }: Props) {
  const { nodes, materials } = useGLTF('/models/PinballMVP_Maker-transformed.glb') as GLTFResult
  const ballInLauncher = useGameStore((state) => state.ballInLauncher)
  const setBallInLauncher = useGameStore((state) => state.setBallInLauncher)

  // Single source of truth for all non-flipper board meshes
  const boardMeshes: MeshDef[] = [
    { geometry: nodes.coll_maker_playfield_collision.geometry, material: materials.PaletteMaterial001, position: [-0.609, -2.903, 7.762] },
    { geometry: nodes.coll_maker_standard_collision_sidewalls.geometry, material: materials.PaletteMaterial002, position: [-0.633, -10.856, 7.78] },
    { geometry: nodes.coll_maker_super_rubber.geometry, material: materials.PaletteMaterial001, position: [-2.105, 0.799, 0.974] },
    { geometry: nodes.coll_maker_metal.geometry, material: materials.PaletteMaterial002, position: [0.313, -2.424, 23.779] },
    { geometry: nodes.coll_maker_slingshot_left.geometry, material: materials.PaletteMaterial002, position: [-0.633, -1.467, 7.78] },
    { geometry: nodes.coll_maker_slingshot_right.geometry, material: materials.PaletteMaterial002, position: [-2.105, 0.799, 0.974] },
    { geometry: nodes.coll_maker_guidance_right.geometry, material: materials.PaletteMaterial001, position: [-1.088, -2.185, 21.588] },
    { geometry: nodes.coll_maker_guidance_left.geometry, material: materials.PaletteMaterial001, position: [-0.633, -1.467, 7.78] },
  ]

  if (withPhysics) {
    return (
      <>
        {/* Visual meshes */}
        {boardMeshes.map((m, i) => (
          <mesh key={i} geometry={m.geometry} material={m.material} position={m.position} />
        ))}

        {/* Static physics colliders */}
        <RigidBody type="fixed" colliders="trimesh" friction={0} restitution={0.3} includeInvisible>
          {boardMeshes.map((m, i) => (
            <mesh key={i} visible={false} geometry={m.geometry} position={m.position} />
          ))}
          {/* Invisible glass panel ceiling */}
          <mesh visible={false} geometry={nodes.coll_maker_glass_panel.geometry} position={[-0.609, -1.388, 7.762]} />
        </RigidBody>

        {/* Gate sensor: détecte quand la bille quitte le plunger */}
        <RigidBody
          type="fixed"
          sensor
          position={[8.4, -1.6, 5.9]}
          rotation={[0, Math.PI / 2.6, 0]}
          onIntersectionEnter={(e) => {
            if (e.other.rigidBodyObject?.name === 'ball') {
              setTimeout(() => setBallInLauncher(false), 500)
            }
          }}
        >
          <CuboidCollider args={[1, 1, 0.2]} />
        </RigidBody>

        {/* Gate: apparaît (visible + collider) seulement après que la bille a quitté le plunger */}
        {!ballInLauncher && (
          <RigidBody type="fixed" colliders="hull" restitution={0}>
            <mesh geometry={nodes.coll_maker_gate.geometry} material={materials.PaletteMaterial002} position={[8.733, -1.272, 5.992]} />
          </RigidBody>
        )}

        {/* Kinematic flippers */}
        <Flipper
          side="left"
          position={[-5.001, -2.901, 26.34]}
          rotation={[0, 0, 0]}
          colliderGeometry={nodes.coll_maker_flipper_left_bottom.geometry}
          visualGeometry={nodes.coll_maker_flipper_left_bottom.geometry}
          visualMaterial={materials.PaletteMaterial002}
        />
        <Flipper
          side="right"
          position={[2.787, -2.901, 26.34]}
          rotation={[0, 0, 0]}
          colliderGeometry={nodes.coll_maker_flipper_right_bottom.geometry}
          visualGeometry={nodes.coll_maker_flipper_right_bottom.geometry}
          visualMaterial={materials.PaletteMaterial002}
        />
      </>
    )
  }

  // Editor mode: plain meshes, no physics
  return (
    <group {...props} dispose={null}>
      {boardMeshes.map((m, i) => (
        <mesh key={i} geometry={m.geometry} material={m.material} position={m.position} />
      ))}
      <mesh geometry={nodes.coll_maker_flipper_left_bottom.geometry} material={materials.PaletteMaterial002} position={[-5.001, -2.901, 26.34]} />
      <mesh geometry={nodes.coll_maker_flipper_right_bottom.geometry} material={materials.PaletteMaterial002} position={[2.787, -2.901, 26.34]} />
    </group>
  )
}

useGLTF.preload('/models/PinballMVP_Maker-transformed.glb')
