/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PinballMVP.glb -T -t -j -o src/components/models/PinballMVP2.tsx 
Files: public/models/PinballMVP.glb [728.59MB] > /Users/adrienallard/Développement/HETIC/Pinball_ThreeJs/frontend/src/components/models/PinballMVP-transformed.glb [24.27MB] (97%)
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";
import { SkeletonUtils } from "three-stdlib";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    visual_ground_2: THREE.Mesh;
    visual_bg_sunset_2: THREE.Mesh;
    visual_env_pyramid: THREE.Mesh;
    visual_env_sand: THREE.Mesh;
    visual_crane: THREE.Mesh;
    visual_env_ruin_left_1: THREE.Mesh;
    visual_env_ruin_right_0: THREE.Mesh;
    env_ruins1_LOD0: THREE.Mesh;
    env_ruins1_LOD0_1: THREE.Mesh;
    oasis_vegetation_back_LOD0: THREE.Mesh;
    oasis_vegetation_back_LOD0_1: THREE.Mesh;
    oasis_vegetation_back_LOD0_2: THREE.Mesh;
    visual_oasis_vegetation_front_5: THREE.Mesh;
    visual_overlap_2: THREE.Mesh;
    mummy_button_LOD0: THREE.Mesh;
    mummy_button_LOD0_1: THREE.Mesh;
    visual_grill: THREE.Mesh;
    visual_oasis_lake_2: THREE.Mesh;
    visual_env_tools: THREE.Mesh;
    visual_nile_vegetables: THREE.Mesh;
    visual_sarcophagus01_basex: THREE.Mesh;
    visual_nile: THREE.Mesh;
    visual_habit_right_9: THREE.Mesh;
    visual_habit_left_7: THREE.Mesh;
    visual_scarab_flasher_01_16: THREE.Mesh;
    visual_scarab_flasher_02_26: THREE.Mesh;
    visual_scarab_flasher_05_18: THREE.Mesh;
    visual_scarab_flasher_plane_01_17: THREE.Mesh;
    visual_scarab_flasher_plane_02_27: THREE.Mesh;
    visual_scarab_flasher_plane_05_19: THREE.Mesh;
    visual_scarab_flasher_03_24: THREE.Mesh;
    visual_scarab_flasher_plane_03_25: THREE.Mesh;
    visual_scarab_flasher_06_20: THREE.Mesh;
    visual_scarab_flasher_07_22: THREE.Mesh;
    visual_scarab_flasher_plane_06_21: THREE.Mesh;
    visual_scarab_flasher_plane_07_23: THREE.Mesh;
    mpf_metal_wires_LOD0: THREE.Mesh;
    mpf_metal_wires_LOD0_1: THREE.Mesh;
    sphinx_1_LOD0: THREE.Mesh;
    sphinx_1_LOD0_1: THREE.Mesh;
    sphinx_2_LOD0: THREE.Mesh;
    sphinx_2_LOD0_1: THREE.Mesh;
    sphinx_3_LOD0: THREE.Mesh;
    sphinx_3_LOD0_1: THREE.Mesh;
    sphinx_7_LOD0: THREE.Mesh;
    sphinx_7_LOD0_1: THREE.Mesh;
    sphinx_8_LOD0: THREE.Mesh;
    sphinx_8_LOD0_1: THREE.Mesh;
    sphinx_base_LOD0: THREE.Mesh;
    sphinx_base_LOD0_1: THREE.Mesh;
    sphinx_6_LOD0: THREE.Mesh;
    sphinx_6_LOD0_1: THREE.Mesh;
    sphinx_4_LOD0: THREE.Mesh;
    sphinx_4_LOD0_1: THREE.Mesh;
    sphinx_5_LOD0: THREE.Mesh;
    sphinx_5_LOD0_1: THREE.Mesh;
    visual_river_water_fall: THREE.Mesh;
    visual_mummy_floor: THREE.Mesh;
    visual_overlap_bottom_3: THREE.Mesh;
    visual_lg_10x: THREE.Mesh;
    visual_lg_2x: THREE.Mesh;
    visual_lg_3x: THREE.Mesh;
    visual_lg_4x: THREE.Mesh;
    visual_lg_5x: THREE.Mesh;
    visual_lg_6x: THREE.Mesh;
    visual_lg_7x: THREE.Mesh;
    visual_lg_8x: THREE.Mesh;
    visual_lg_9x: THREE.Mesh;
    visual_locker: THREE.Mesh;
    visual_ramp_back: THREE.Mesh;
    visual_lg_crocos_c1_0: THREE.Mesh;
    visual_lg_crocos_c2_1: THREE.Mesh;
    visual_lg_crocos_o1_4: THREE.Mesh;
    visual_lg_crocos_o2_2: THREE.Mesh;
    visual_lg_crocos_r_3: THREE.Mesh;
    visual_lg_crocos_s_5: THREE.Mesh;
    visual_miniplayfield: THREE.Mesh;
    visual_obj_flipper_mini_left: THREE.Mesh;
    visual_obj_flipper_mini_left001: THREE.Mesh;
    visual_obj_flipper_mini_right: THREE.Mesh;
    visual_obj_flipper_mini_right001: THREE.Mesh;
    visual_rollover_top_1: THREE.Mesh;
    visual_rollover_top_2: THREE.Mesh;
    visual_rollover_top_3: THREE.Mesh;
    visual_droptarget_mpf_01_gfx: THREE.Mesh;
    visual_droptarget_mpf_02_gfx: THREE.Mesh;
    visual_droptarget_mpf_03_gfx: THREE.Mesh;
    visual_droptarget_mpf_04_gfx: THREE.Mesh;
    visual_droptarget_mpf_05_gfx: THREE.Mesh;
    visual_shadow_flipper_mini_right: THREE.Mesh;
    visual_shadow_flipper_mini_right001: THREE.Mesh;
    visual_river_water: THREE.Mesh;
    visual_ramp_right_sand: THREE.Mesh;
    middle_stuff_top_LOD0: THREE.Mesh;
    middle_stuff_top_LOD0_1: THREE.Mesh;
    visual_bridge_part_01: THREE.Mesh;
    visual_bridge_part_02: THREE.Mesh;
    visual_bridge_part_03: THREE.Mesh;
    visual_bridge_part_04: THREE.Mesh;
    visual_mpf_spinner_obj: THREE.Mesh;
    visual_gate_mpf_left_gfx_8: THREE.Mesh;
    visual_gate_mpf_right_gfx_3: THREE.Mesh;
    obj_target_LOD0: THREE.Mesh;
    obj_target_LOD0_1: THREE.Mesh;
    visual_obj_target001_6: THREE.Mesh;
    visual_lg_bridge_on_the_nile: THREE.Mesh;
    visual_lg_bridge_1: THREE.Mesh;
    visual_lg_sphinx_83: THREE.Mesh;
    visual_lg_underworld_86: THREE.Mesh;
    visual_lg_bonus_multi_85: THREE.Mesh;
    visual_lg_bridge_2: THREE.Mesh;
    visual_lg_lock_mpf_84: THREE.Mesh;
    visual_lg_mummy_mpf_82: THREE.Mesh;
    visual_lg_sun_clock_16: THREE.Mesh;
    visual_lg_sun_clock_18: THREE.Mesh;
    visual_lg_sun_clock_20: THREE.Mesh;
    visual_lg_sun_clock_22: THREE.Mesh;
    visual_lg_sun_clock_24: THREE.Mesh;
    visual_lg_sun_clock_26: THREE.Mesh;
    visual_lg_sun_clock_28: THREE.Mesh;
    visual_lg_sun_clock_30: THREE.Mesh;
    visual_spindisk_mpf: THREE.Mesh;
    visual_diverter_to_vuk_0: THREE.Mesh;
    visual_lg_maze_blaze_116: THREE.Mesh;
    visual_lg_scarab_trouble_5: THREE.Mesh;
    visual_lg_jackpot_92: THREE.Mesh;
    visual_lg_maze_blaze_118: THREE.Mesh;
    visual_lg_scarab_trouble_105: THREE.Mesh;
    visual_lg_army_of_anubis_70: THREE.Mesh;
    visual_lg_croco_madness_115: THREE.Mesh;
    visual_lg_croco_madness_97: THREE.Mesh;
    visual_lg_jackpot_101: THREE.Mesh;
    visual_lg_jackpot_102: THREE.Mesh;
    visual_lg_jackpot_104: THREE.Mesh;
    visual_lg_jackpot_106: THREE.Mesh;
    visual_lg_jackpot_111: THREE.Mesh;
    visual_lg_jackpot_4: THREE.Mesh;
    visual_lg_kickback_95: THREE.Mesh;
    visual_lg_lock_91: THREE.Mesh;
    visual_lg_maze_blaze_113: THREE.Mesh;
    visual_lg_mummy_100: THREE.Mesh;
    visual_lg_mummy_103: THREE.Mesh;
    visual_lg_mummy_108: THREE.Mesh;
    visual_lg_mummy_109: THREE.Mesh;
    visual_lg_mummy_114: THREE.Mesh;
    visual_lg_mummy_90: THREE.Mesh;
    visual_lg_mummy_99: THREE.Mesh;
    visual_lg_oasis_54: THREE.Mesh;
    visual_lg_palm_tree_107: THREE.Mesh;
    visual_lg_palm_tree_93: THREE.Mesh;
    visual_lg_palm_tree_98: THREE.Mesh;
    visual_lg_pyramid_64: THREE.Mesh;
    visual_lg_tomb_runner_55: THREE.Mesh;
    visual_lg_wizard_mode_62: THREE.Mesh;
    visual_lg_kickback_112: THREE.Mesh;
    visual_lg_egypt_e: THREE.Mesh;
    visual_lg_egypt_g: THREE.Mesh;
    visual_lg_egypt_y: THREE.Mesh;
    visual_lg_extra_ball_65: THREE.Mesh;
    visual_lg_jackpot_96: THREE.Mesh;
    visual_lg_mummy_87: THREE.Mesh;
    visual_lg_palm_tree_110: THREE.Mesh;
    visual_lg_palm_tree_94: THREE.Mesh;
    visual_lg_scarab_trouble_117: THREE.Mesh;
    screws_LOD0: THREE.Mesh;
    screws_LOD0_1: THREE.Mesh;
    visual_obj_flipper_left_bottom: THREE.Mesh;
    visual_obj_flipper_right_bottom: THREE.Mesh;
    visual_lg_ball_37: THREE.Mesh;
    visual_obj_gate_5: THREE.Mesh;
    visual_ramp_left_sand: THREE.Mesh;
    visual_pyramid: THREE.Mesh;
    visual_scarab_flasher_04_15: THREE.Mesh;
    visual_scarab_flasher_plane_04_14: THREE.Mesh;
    obj_spinner_LOD0: THREE.Mesh;
    obj_spinner_LOD0_1: THREE.Mesh;
    visual_lg_gi_lamps_4: THREE.Mesh;
    GI_bulbs_gfx_LOD0: THREE.Mesh;
    GI_bulbs_gfx_LOD0_1: THREE.Mesh;
    visual_middle_stuff_overlap: THREE.Mesh;
    visual_slingshot_flash_obj_left: THREE.Mesh;
    visual_slingshot_flash_obj_right: THREE.Mesh;
    visual_stared_posts: THREE.Mesh;
    visual_screws_slingshots: THREE.Mesh;
    visual_lg_kickback_right_36: THREE.Mesh;
    visual_metals_slingshot: THREE.Mesh;
    visual_slingshot_right_shot: THREE.Mesh;
    visual_slingshot_left_shot: THREE.Mesh;
    visual_lg_kickback_left_40: THREE.Mesh;
    visual_lg_egypt_p: THREE.Mesh;
    visual_lg_egypt_t: THREE.Mesh;
    visual_metal_post_outlanes_up: THREE.Mesh;
    visual_sidewalls: THREE.Mesh;
    visual_right_kickback_door: THREE.Mesh;
    visual_diverter_plunger_back: THREE.Mesh;
    visual_diverter_plunger: THREE.Mesh;
    holes_nocoll_LOD0: THREE.Mesh;
    holes_nocoll_LOD0_1: THREE.Mesh;
    waterlvl_LOD0: THREE.Mesh;
    waterlvl_LOD0_1: THREE.Mesh;
    waterlvl_LOD0_2: THREE.Mesh;
    visual_ball_rollover: THREE.Mesh;
    visual_bonus_05: THREE.Mesh;
    visual_bonus_01: THREE.Mesh;
    visual_bonus_02: THREE.Mesh;
    visual_bonus_03: THREE.Mesh;
    visual_bonus_04: THREE.Mesh;
    posts_outlane_LOD0: THREE.Mesh;
    posts_outlane_LOD0_1: THREE.Mesh;
    visual_playfield: THREE.Mesh;
    visual_diverter_left_orbit_1: THREE.Mesh;
    visual_pf_door_right: THREE.Mesh;
    visual_pf_door_left: THREE.Mesh;
    visual_under_pf: THREE.Mesh;
    visual_anu_card_01_gfx: THREE.Mesh;
    visual_anu_card_02_gfx: THREE.Mesh;
    visual_anu_card_03_gfx: THREE.Mesh;
    visual_anu_card_04_gfx: THREE.Mesh;
    visual_anu_card_05_gfx: THREE.Mesh;
    visual_lg_army_of_anubis_02: THREE.Mesh;
    visual_plunger: THREE.Mesh;
    visual_diverter_right_orbit: THREE.Mesh;
    visual_diverter_center03: THREE.Mesh;
    visual_diverter_center01: THREE.Mesh;
    visual_diverter_center02_21: THREE.Mesh;
    coll_habit_left: THREE.Mesh;
    coll_habit_mini_pf: THREE.Mesh;
    coll_habit_right: THREE.Mesh;
    coll_ramp_back: THREE.Mesh;
    coll_top: THREE.Mesh;
    coll_standard_collision: THREE.Mesh;
    coll_habit_vuk: THREE.Mesh;
    coll_sphinx_bottom: THREE.Mesh;
    coll_mummy: THREE.Mesh;
    coll_scarabeus: THREE.Mesh;
    coll_locker: THREE.Mesh;
    coll_ramp_back001: THREE.Mesh;
    coll_flipper_mini_left: THREE.Mesh;
    coll_flipper_mini_left001: THREE.Mesh;
    coll_flipper_mini_right: THREE.Mesh;
    coll_flipper_mini_right001: THREE.Mesh;
    coll_bumper01: THREE.Mesh;
    coll_bumper02: THREE.Mesh;
    coll_bumper03: THREE.Mesh;
    coll_bumper04: THREE.Mesh;
    coll_locker_launch: THREE.Mesh;
    coll_mpf_spindisk_wall: THREE.Mesh;
    coll_blunt_rubber: THREE.Mesh;
    coll_droptarget_mpf_01: THREE.Mesh;
    coll_droptarget_mpf_02: THREE.Mesh;
    coll_droptarget_mpf_03: THREE.Mesh;
    coll_droptarget_mpf_04: THREE.Mesh;
    coll_droptarget_mpf_05: THREE.Mesh;
    coll_mpf_metal_wires: THREE.Mesh;
    coll_scoops01_6: THREE.Mesh;
    coll_ramp_right: THREE.Mesh;
    coll_rubber: THREE.Mesh;
    coll_super_rubber: THREE.Mesh;
    coll_nile: THREE.Mesh;
    coll_mpf_spinner: THREE.Mesh;
    coll_miniplayfield: THREE.Mesh;
    coll_bridge_part_01: THREE.Mesh;
    coll_bridge_part_02: THREE.Mesh;
    coll_bridge_part_03: THREE.Mesh;
    coll_bridge_part_04: THREE.Mesh;
    coll_gate_mpf_left: THREE.Mesh;
    coll_gate_mpf_right_2: THREE.Mesh;
    coll_target: THREE.Mesh;
    coll_target001: THREE.Mesh;
    coll_spindisk_mpf: THREE.Mesh;
    coll_diverter_to_vuk: THREE.Mesh;
    coll_flipper_left_bottom: THREE.Mesh;
    coll_flipper_right_bottom: THREE.Mesh;
    coll_gate: THREE.Mesh;
    coll_safe_pyramid: THREE.Mesh;
    coll_pyramid: THREE.Mesh;
    coll_pyramid_temporary: THREE.Mesh;
    coll_pyramid_wall_03: THREE.Mesh;
    coll_pyramid_door: THREE.Mesh;
    coll_spinner_10: THREE.Mesh;
    coll_metal: THREE.Mesh;
    coll_scoops: THREE.Mesh;
    coll_ramp_left: THREE.Mesh;
    coll_anubis_head_hole: THREE.Mesh;
    coll_locker_door_11: THREE.Mesh;
    coll_fr_slingshot_flasher_left: THREE.Mesh;
    coll_fr_slingshot_flasher_right: THREE.Mesh;
    coll_ramp_metal: THREE.Mesh;
    coll_sidewalls: THREE.Mesh;
    coll_left_kickback_door: THREE.Mesh;
    coll_diverter_plunger_back: THREE.Mesh;
    coll_diverter_plunger: THREE.Mesh;
    coll_anubis_mouth: THREE.Mesh;
    coll_posts_outlane: THREE.Mesh;
    coll_playfield_collision: THREE.Mesh;
    coll_left_hole: THREE.Mesh;
    coll_diverter_left_orbit_0: THREE.Mesh;
    coll_under_pf: THREE.Mesh;
    coll_anu_card_01: THREE.Mesh;
    coll_anu_card_02: THREE.Mesh;
    coll_anu_card_03: THREE.Mesh;
    coll_anu_card_04: THREE.Mesh;
    coll_anu_card_05: THREE.Mesh;
    coll_diverter_right_orbit: THREE.Mesh;
    coll_diverter_center02_20: THREE.Mesh;
    coll_diverter_center03: THREE.Mesh;
    coll_diverter_center01: THREE.Mesh;
    coll_right_sling_collision_bottom: THREE.Mesh;
    coll_left_sling_collision_bottom: THREE.Mesh;
    coll_left_sling_collision_top: THREE.Mesh;
    coll_right_sling_collision_top: THREE.Mesh;
    sensor_mpf_presence_0: THREE.Mesh;
    sensor_mini_left001_arm: THREE.Mesh;
    sensor_mini_left_arm: THREE.Mesh;
    sensor_mini_right001_arm: THREE.Mesh;
    sensor_mini_right_arm: THREE.Mesh;
    sensor_nile: THREE.Mesh;
    sensor_bridge_left: THREE.Mesh;
    sensor_bridge_right: THREE.Mesh;
    sensor_bridge: THREE.Mesh;
    sensor_left_bottom_arm: THREE.Mesh;
    sensor_right_bottom_arm: THREE.Mesh;
    stick_barrier: THREE.Mesh;
    TrialHoleDrainSensor: THREE.Mesh;
    launched: THREE.Mesh;
    sensor_sinkhole_left: THREE.Mesh;
    ballHouse: THREE.Mesh;
    ballhouse_box: THREE.Mesh;
    path_scarabs_center_hole: THREE.Mesh;
    path_scarabs_left_hole: THREE.Mesh;
    path_scarabs_right_hole: THREE.Mesh;
    visual_anubis: THREE.SkinnedMesh;
    visual_ornate_torch_04_20: THREE.SkinnedMesh;
    coll_locker_door_2001: THREE.SkinnedMesh;
    visual_locker_door_2: THREE.SkinnedMesh;
    visual_sarcophagus01_door_3001: THREE.SkinnedMesh;
    visual_anubis_under_pf_11001: THREE.SkinnedMesh;
    visual_scarabeus: THREE.SkinnedMesh;
    visual_anubis_under_pf2001: THREE.SkinnedMesh;
    visual_torch_left_24001: THREE.SkinnedMesh;
    visual_torch_right_28001: THREE.SkinnedMesh;
    visual_ornate_torch_01_14001: THREE.SkinnedMesh;
    visual_ornate_torch_03_17: THREE.SkinnedMesh;
    visual_crochead1001: THREE.SkinnedMesh;
    visual_crochead2_19001: THREE.SkinnedMesh;
    visual_crochead3001: THREE.SkinnedMesh;
    visual_crochead4_18001: THREE.SkinnedMesh;
    visual_waterlvl_bubble_2001: THREE.SkinnedMesh;
    visual_crocodile_plunger: THREE.SkinnedMesh;
    mummy_LOD0: THREE.SkinnedMesh;
    mummy_LOD0_1: THREE.SkinnedMesh;
    mummy_LOD0_2: THREE.SkinnedMesh;
    visual_slingshot_left_10001: THREE.SkinnedMesh;
    visual_slingshot_right_7001: THREE.SkinnedMesh;
    root_crocodile: THREE.Bone;
    anubis_root: THREE.Bone;
    mummy_root: THREE.Bone;
    Root_Torches: THREE.Bone;
    locker_root: THREE.Bone;
    sarcophagus01_root: THREE.Bone;
    anubis_undpf_root: THREE.Bone;
    scarabeus_root: THREE.Bone;
    anubis_undpf_root_1: THREE.Bone;
    Root_Torches_1: THREE.Bone;
    Root_Torches_2: THREE.Bone;
    Root_Torches_3: THREE.Bone;
    Root_Torches_4: THREE.Bone;
    crochead_root: THREE.Bone;
    crochead_root_1: THREE.Bone;
    crochead_root_2: THREE.Bone;
    crochead_root_3: THREE.Bone;
    root_left_sling: THREE.Bone;
    root_right_sling: THREE.Bone;
    waterlevel_group: THREE.Bone;
  };
  materials: {
    M_sand_tile: THREE.MeshStandardMaterial;
    M_bg_sunset: THREE.MeshStandardMaterial;
    M_env_pyramid: THREE.MeshStandardMaterial;
    M_bg_env_ground: THREE.MeshStandardMaterial;
    M_crane: THREE.MeshStandardMaterial;
    M_overlap: THREE.MeshStandardMaterial;
    M_ruin_right: THREE.MeshStandardMaterial;
    M_env_ruins1: THREE.MeshStandardMaterial;
    M_broken_stone1: THREE.MeshStandardMaterial;
    M_vegetation: THREE.MeshStandardMaterial;
    M_palm_bark: THREE.MeshStandardMaterial;
    M_mummy_button: THREE.MeshStandardMaterial;
    M_mummy_button_alpha: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    M_env_tools: THREE.MeshStandardMaterial;
    M_vegetation_02: THREE.MeshStandardMaterial;
    M_nile_ramp: THREE.MeshStandardMaterial;
    scarab_flasher: THREE.MeshStandardMaterial;
    M_sphinx: THREE.MeshStandardMaterial;
    m_mummy_path: THREE.MeshStandardMaterial;
    lamp_playfield: THREE.MeshStandardMaterial;
    M_ramp_back: THREE.MeshStandardMaterial;
    M_miniplayfield: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_left: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_left2: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_right: THREE.MeshStandardMaterial;
    M_flipper_mini_arm_right2: THREE.MeshStandardMaterial;
    M_midlestuff: THREE.MeshStandardMaterial;
    flipper_arms_shadow: THREE.MeshStandardMaterial;
    M_ramps: THREE.MeshStandardMaterial;
    M_bridge: THREE.MeshStandardMaterial;
    target: THREE.MeshStandardMaterial;
    ["metal_sidewalls.001"]: THREE.MeshStandardMaterial;
    M_spindisk: THREE.MeshStandardMaterial;
    M_flipper_arm_left: THREE.MeshStandardMaterial;
    M_flipper_arm_right: THREE.MeshStandardMaterial;
    M_pyramid__Inst: THREE.MeshStandardMaterial;
    M_spinner: THREE.MeshStandardMaterial;
    lamp_playfield_white: THREE.MeshStandardMaterial;
    M_slingshot_flasher_obj: THREE.MeshStandardMaterial;
    ["M_playfield_cutout.001"]: THREE.MeshStandardMaterial;
    M_black: THREE.MeshStandardMaterial;
    gold: THREE.MeshStandardMaterial;
    waterlvl: THREE.MeshStandardMaterial;
    playfield: THREE.MeshStandardMaterial;
    M_underplayfield: THREE.MeshStandardMaterial;
    M_army_of_anubis: THREE.MeshStandardMaterial;
    M_anubis_head_eyes: THREE.MeshStandardMaterial;
    M_anubis_head: THREE.MeshStandardMaterial;
    M_Torches: THREE.MeshStandardMaterial;
    M_locker: THREE.MeshStandardMaterial;
    M_sarcophagus: THREE.MeshStandardMaterial;
    M_scarabeus: THREE.MeshStandardMaterial;
    M_crocodile_plunger: THREE.MeshStandardMaterial;
    water_level_bubble: THREE.MeshStandardMaterial;
    M_mummy: THREE.MeshStandardMaterial;
    M_mummy_eye: THREE.MeshStandardMaterial;
    M_mummy_jewel: THREE.MeshStandardMaterial;
    rubber: THREE.MeshStandardMaterial;
  };

  animations: THREE.AnimationClip[];
};

export default function PinballMVP2(props: JSX.IntrinsicElements["group"]) {
  const { scene } = useGLTF("/models/PinballMVP2-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.root_crocodile} />
      <primitive object={nodes.anubis_root} />
      <primitive object={nodes.mummy_root} />
      <primitive object={nodes.Root_Torches} />
      <primitive object={nodes.locker_root} />
      <primitive object={nodes.sarcophagus01_root} />
      <primitive object={nodes.anubis_undpf_root} />
      <primitive object={nodes.scarabeus_root} />
      <primitive object={nodes.anubis_undpf_root_1} />
      <primitive object={nodes.Root_Torches_1} />
      <primitive object={nodes.Root_Torches_2} />
      <primitive object={nodes.Root_Torches_3} />
      <primitive object={nodes.Root_Torches_4} />
      <primitive object={nodes.crochead_root} />
      <primitive object={nodes.crochead_root_1} />
      <primitive object={nodes.crochead_root_2} />
      <primitive object={nodes.crochead_root_3} />
      <primitive object={nodes.root_left_sling} />
      <primitive object={nodes.root_right_sling} />
      <primitive object={nodes.waterlevel_group} />
      <mesh
        geometry={nodes.visual_ground_2.geometry}
        material={materials.M_sand_tile}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bg_sunset_2.geometry}
        material={materials.M_bg_sunset}
        position={[-1.212, 7.019, -181.084]}
        scale={[116.878, 86.342, 116.878]}
      />
      <mesh
        geometry={nodes.visual_env_pyramid.geometry}
        material={materials.M_env_pyramid}
        position={[-98.587, 23.747, -79.016]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_sand.geometry}
        material={materials.M_bg_env_ground}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_crane.geometry}
        material={materials.M_crane}
        position={[54.899, 7.531, 42.026]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_ruin_left_1.geometry}
        material={materials.M_overlap}
        position={[-35.975, 4.047, 33.058]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_ruin_right_0.geometry}
        material={materials.M_ruin_right}
        position={[49.166, 2.842, -1.616]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.env_ruins1_LOD0.geometry}
          material={materials.M_env_ruins1}
        />
        <mesh
          geometry={nodes.env_ruins1_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0.geometry}
          material={materials.M_vegetation}
        />
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0_1.geometry}
          material={materials.M_palm_bark}
        />
        <mesh
          geometry={nodes.oasis_vegetation_back_LOD0_2.geometry}
          material={materials.M_vegetation}
        />
      </group>
      <mesh
        geometry={nodes.visual_oasis_vegetation_front_5.geometry}
        material={materials.M_vegetation}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_overlap_2.geometry}
        material={materials.M_overlap}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.mummy_button_LOD0.geometry}
          material={materials.M_mummy_button}
        />
        <mesh
          geometry={nodes.mummy_button_LOD0_1.geometry}
          material={materials.M_mummy_button_alpha}
        />
      </group>
      <mesh
        geometry={nodes.visual_grill.geometry}
        material={materials.M_ruin_right}
        position={[33.589, -2.251, 56.567]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_oasis_lake_2.geometry}
        material={materials.PaletteMaterial001}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_env_tools.geometry}
        material={materials.M_env_tools}
        position={[-14.75, -2.125, 58.467]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_nile_vegetables.geometry}
        material={materials.M_vegetation_02}
        position={[4.471, 3.698, -26.384]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_sarcophagus01_basex.geometry}
        material={materials.M_sarcophagus}
        position={[26.613, 4.618, -3.19]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_nile.geometry}
        material={materials.M_nile_ramp}
        position={[4.471, 3.698, -26.384]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_habit_right_9.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.237, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_habit_left_7.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_01_16.geometry}
        material={materials.scarab_flasher}
        position={[-25.043, 3.413, 11.054]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_02_26.geometry}
        material={materials.scarab_flasher}
        position={[17.054, -1.635, 19.881]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_05_18.geometry}
        material={materials.scarab_flasher}
        position={[-31.222, -1.586, -20.613]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_01_17.geometry}
        material={materials.PaletteMaterial002}
        position={[-25.14, 3.73, 11.062]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_02_27.geometry}
        material={materials.PaletteMaterial002}
        position={[17.158, -1.257, 19.863]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_05_19.geometry}
        material={materials.PaletteMaterial002}
        position={[-31.2, -1.162, -20.648]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_03_24.geometry}
        material={materials.scarab_flasher}
        position={[19.395, -1.669, -24.239]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_03_25.geometry}
        material={materials.PaletteMaterial002}
        position={[19.547, -1.351, -24.262]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_06_20.geometry}
        material={materials.scarab_flasher}
        position={[-9.856, 9.687, -37.412]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_07_22.geometry}
        material={materials.scarab_flasher}
        position={[19.388, 9.997, -32.615]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_06_21.geometry}
        material={materials.PaletteMaterial002}
        position={[-9.931, 10.005, -37.43]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_07_23.geometry}
        material={materials.PaletteMaterial002}
        position={[19.441, 10.315, -32.642]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.mpf_metal_wires_LOD0.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.mpf_metal_wires_LOD0_1.geometry}
          material={materials.rubber}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_1_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_1_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_2_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_2_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_3_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_3_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_7_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_7_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_8_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_8_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_base_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_base_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_6_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_6_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_4_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_4_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <group
        position={[-15.427, 6.732, -37.568]}
        rotation={[0, 0.41, 0]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.sphinx_5_LOD0.geometry}
          material={materials.M_sphinx}
        />
        <mesh
          geometry={nodes.sphinx_5_LOD0_1.geometry}
          material={materials.M_broken_stone1}
        />
      </group>
      <mesh
        geometry={nodes.visual_river_water_fall.geometry}
        material={materials.PaletteMaterial001}
        position={[1.424, -1.112, -8.611]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_mummy_floor.geometry}
        material={materials.m_mummy_path}
        position={[23.048, -2.621, 35.828]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_overlap_bottom_3.geometry}
        material={materials.M_overlap}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_10x.geometry}
        material={materials.lamp_playfield}
        position={[18.346, -2.282, 50.746]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_2x.geometry}
        material={materials.lamp_playfield}
        position={[1.817, -2.192, 60.482]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_3x.geometry}
        material={materials.lamp_playfield}
        position={[3.925, -2.145, 59.671]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_4x.geometry}
        material={materials.lamp_playfield}
        position={[6.202, -2.143, 58.486]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_5x.geometry}
        material={materials.lamp_playfield}
        position={[8.061, -2.226, 57.184]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_6x.geometry}
        material={materials.lamp_playfield}
        position={[10.229, -2.239, 55.92]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_7x.geometry}
        material={materials.lamp_playfield}
        position={[12.035, -2.203, 54.793]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_8x.geometry}
        material={materials.lamp_playfield}
        position={[14.214, -2.158, 53.417]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_9x.geometry}
        material={materials.lamp_playfield}
        position={[16.227, -2.171, 52.161]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_locker.geometry}
        material={materials.M_locker}
        position={[13.234, 11.209, -35.046]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_ramp_back.geometry}
        material={materials.M_ramp_back}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_c1_0.geometry}
        material={materials.lamp_playfield}
        position={[0.322, 11.838, -43.547]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_c2_1.geometry}
        material={materials.lamp_playfield}
        position={[0.341, 9.884, -43.543]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_o1_4.geometry}
        material={materials.lamp_playfield}
        position={[7.957, 11.842, -43.561]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_o2_2.geometry}
        material={materials.lamp_playfield}
        position={[4.142, 9.897, -43.603]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_r_3.geometry}
        material={materials.lamp_playfield}
        position={[4.089, 11.861, -43.603]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_crocos_s_5.geometry}
        material={materials.lamp_playfield}
        position={[7.982, 9.869, -43.561]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_miniplayfield.geometry}
        material={materials.M_miniplayfield}
        position={[-2.49, 6.799, -32.435]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_mini_left.geometry}
        material={materials.M_flipper_mini_arm_left}
        position={[-17.148, 6.82, -22.066]}
        rotation={[0, -0.855, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_mini_left001.geometry}
        material={materials.M_flipper_mini_arm_left2}
        position={[11.295, 6.82, -22.523]}
        rotation={[0, -1.012, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_mini_right.geometry}
        material={materials.M_flipper_mini_arm_right}
        position={[-1.759, 6.82, -22.973]}
        rotation={[0, 0.96, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_mini_right001.geometry}
        material={materials.M_flipper_mini_arm_right2}
        position={[23.193, 6.82, -19.859]}
        rotation={[0, 0.367, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_rollover_top_1.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.31, 6.971, -41.068]}
        rotation={[0, 0.262, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_rollover_top_2.geometry}
        material={materials.PaletteMaterial002}
        position={[4.422, 6.971, -41.134]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_rollover_top_3.geometry}
        material={materials.PaletteMaterial002}
        position={[9.211, 6.971, -41.059]}
        rotation={[0, -0.279, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_01_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-17.016, 6.277, -28.049]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[94.51, 94.51, 74.916]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_02_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-17.295, 6.277, -28.532]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[94.51, 94.51, 74.916]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_03_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-17.574, 6.277, -29.016]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[94.51, 94.51, 74.916]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_04_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-17.853, 6.277, -29.499]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[94.51, 94.51, 74.916]}
      />
      <mesh
        geometry={nodes.visual_droptarget_mpf_05_gfx.geometry}
        material={materials.M_midlestuff}
        position={[-18.132, 6.277, -29.983]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[94.51, 94.51, 74.916]}
      />
      <mesh
        geometry={nodes.visual_shadow_flipper_mini_right.geometry}
        material={materials.flipper_arms_shadow}
        position={[-2.849, 6.839, -21.243]}
        rotation={[0, 0.96, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_shadow_flipper_mini_right001.geometry}
        material={materials.flipper_arms_shadow}
        position={[21.322, 6.839, -19.034]}
        rotation={[0, 0.367, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_river_water.geometry}
        material={materials.PaletteMaterial001}
        position={[4.777, 3.016, -26.049]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_ramp_right_sand.geometry}
        material={materials.M_ramps}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <group position={[-3.899, -2.357, -3.675]} scale={94.51}>
        <mesh
          geometry={nodes.middle_stuff_top_LOD0.geometry}
          material={materials.M_midlestuff}
        />
        <mesh
          geometry={nodes.middle_stuff_top_LOD0_1.geometry}
          material={materials.rubber}
        />
      </group>
      <mesh
        geometry={nodes.visual_bridge_part_01.geometry}
        material={materials.M_bridge}
        position={[-0.049, 6.744, -28.022]}
        rotation={[0, 0.122, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bridge_part_02.geometry}
        material={materials.M_bridge}
        position={[2.087, 6.744, -28.222]}
        rotation={[0, 0.105, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bridge_part_03.geometry}
        material={materials.M_bridge}
        position={[4.223, 6.744, -28.12]}
        rotation={[0, 0.087, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bridge_part_04.geometry}
        material={materials.M_bridge}
        position={[6.359, 6.744, -27.664]}
        rotation={[0, 0.07, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_mpf_spinner_obj.geometry}
        material={materials.PaletteMaterial002}
        position={[-5.139, 6.799, -34.48]}
        rotation={[0, -1.309, Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_gate_mpf_left_gfx_8.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.513, 10.464, -41.991]}
        rotation={[Math.PI / 2, 0, 1.466]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_gate_mpf_right_gfx_3.geometry}
        material={materials.PaletteMaterial002}
        position={[11.917, 10.464, -41.834]}
        rotation={[Math.PI / 2, 0, -1.431]}
        scale={94.51}
      />
      <group
        position={[19.009, 6.813, -30.501]}
        rotation={[3.141, -1.32, 3.141]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.obj_target_LOD0.geometry}
          material={materials.target}
        />
        <mesh
          geometry={nodes.obj_target_LOD0_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.visual_obj_target001_6.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[23.593, 6.813, -25.943]}
        rotation={[3.142, -0.465, 3.142]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_bridge_on_the_nile.geometry}
        material={materials.lamp_playfield}
        position={[-3.597, 6.847, -25.884]}
        rotation={[0, 0.262, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_bridge_1.geometry}
        material={materials.lamp_playfield}
        position={[-3.371, 6.828, -26.867]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sphinx_83.geometry}
        material={materials.lamp_playfield}
        position={[-10.882, 6.828, -27.289]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_underworld_86.geometry}
        material={materials.lamp_playfield}
        position={[-15.648, 6.828, -25.323]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_bonus_multi_85.geometry}
        material={materials.lamp_playfield}
        position={[21.574, 6.828, -24.621]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_bridge_2.geometry}
        material={materials.lamp_playfield}
        position={[12.036, 6.828, -26.103]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_lock_mpf_84.geometry}
        material={materials.lamp_playfield}
        position={[15.817, 6.828, -29.679]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_mpf_82.geometry}
        material={materials.lamp_playfield}
        position={[12.581, 6.828, -29.274]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_16.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_18.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_20.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_22.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_24.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_26.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_28.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        rotation={[0, -Math.PI / 4, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_sun_clock_30.geometry}
        material={materials.lamp_playfield}
        position={[-5.139, 6.799, -34.48]}
        rotation={[0, -1.571, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_spindisk_mpf.geometry}
        material={materials.M_spindisk}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_to_vuk_0.geometry}
        material={materials.M_ramp_back}
        position={[25.162, -5.158, -18.288]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_maze_blaze_116.geometry}
        material={materials.lamp_playfield}
        position={[16.287, -5.129, 6.2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_scarab_trouble_5.geometry}
        material={materials.lamp_playfield}
        position={[10.948, -5.129, 6]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_92.geometry}
        material={materials.lamp_playfield}
        position={[0.643, -5.129, -3.239]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_maze_blaze_118.geometry}
        material={materials.lamp_playfield}
        position={[1.864, -5.12, -13.656]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_scarab_trouble_105.geometry}
        material={materials.lamp_playfield}
        position={[1.364, -5.15, -8.664]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_army_of_anubis_70.geometry}
        material={materials.lamp_playfield}
        position={[8.831, -5.129, 10.686]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_croco_madness_115.geometry}
        material={materials.lamp_playfield}
        position={[-14.086, -5.129, 14.364]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_croco_madness_97.geometry}
        material={materials.lamp_playfield}
        position={[12.182, -5.129, 16.165]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_101.geometry}
        material={materials.lamp_playfield}
        position={[-13.638, -5.129, 2.449]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_102.geometry}
        material={materials.lamp_playfield}
        position={[6.948, -5.129, 15.673]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_104.geometry}
        material={materials.lamp_playfield}
        position={[-18.794, -5.129, 5.147]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_106.geometry}
        material={materials.lamp_playfield}
        position={[5.839, -5.129, 2.442]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_111.geometry}
        material={materials.lamp_playfield}
        position={[14.009, -5.129, 11.205]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_4.geometry}
        material={materials.lamp_playfield}
        position={[-9.091, -5.129, 1.788]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_95.geometry}
        material={materials.lamp_playfield}
        position={[-14.782, -5.129, -1.656]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_lock_91.geometry}
        material={materials.lamp_playfield}
        position={[-4.842, -5.129, -4.833]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_maze_blaze_113.geometry}
        material={materials.lamp_playfield}
        position={[-21.13, -5.129, 0.146]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_100.geometry}
        material={materials.lamp_playfield}
        position={[5.285, -5.129, 20.283]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_103.geometry}
        material={materials.lamp_playfield}
        position={[-4.522, -5.129, -0.563]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_108.geometry}
        material={materials.lamp_playfield}
        position={[-12.98, -5.129, 18.539]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_109.geometry}
        material={materials.lamp_playfield}
        position={[10.148, -5.129, 19.825]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_114.geometry}
        material={materials.lamp_playfield}
        position={[3.712, -5.129, 11.065]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_90.geometry}
        material={materials.lamp_playfield}
        position={[0.154, -5.129, 1.756]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_99.geometry}
        material={materials.lamp_playfield}
        position={[-12.351, -5.129, 7.266]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_oasis_54.geometry}
        material={materials.lamp_playfield}
        position={[4.884, -5.129, 6.929]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_107.geometry}
        material={materials.lamp_playfield}
        position={[8.74, -5.129, 23.511]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_93.geometry}
        material={materials.lamp_playfield}
        position={[2.91, -5.129, 14.92]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_98.geometry}
        material={materials.lamp_playfield}
        position={[-11.07, -5.129, 10.881]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_pyramid_64.geometry}
        material={materials.lamp_playfield}
        position={[-9.743, -5.129, -3.895]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_tomb_runner_55.geometry}
        material={materials.lamp_playfield}
        position={[-16.463, -5.129, 9.827]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_wizard_mode_62.geometry}
        material={materials.lamp_playfield}
        position={[-4.179, -5.129, 3.792]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_112.geometry}
        material={materials.lamp_playfield}
        position={[6.811, -5.129, -1.684]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_e.geometry}
        material={materials.lamp_playfield}
        position={[-26.805, -5.129, 29.013]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_g.geometry}
        material={materials.lamp_playfield}
        position={[-22.851, -5.129, 29.01]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_y.geometry}
        material={materials.lamp_playfield}
        position={[-18.839, -5.129, 29.012]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_extra_ball_65.geometry}
        material={materials.lamp_playfield}
        position={[-21, -5.129, 22.729]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_jackpot_96.geometry}
        material={materials.lamp_playfield}
        position={[-18.234, -5.129, 20.697]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_mummy_87.geometry}
        material={materials.lamp_playfield}
        position={[-15.601, -5.129, 24.916]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_110.geometry}
        material={materials.lamp_playfield}
        position={[-11.26, -5.129, 21.945]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_palm_tree_94.geometry}
        material={materials.lamp_playfield}
        position={[-13.347, -5.129, 27.901]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_scarab_trouble_117.geometry}
        material={materials.lamp_playfield}
        position={[-21.451, -5.129, 15.95]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.screws_LOD0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.screws_LOD0_1.geometry}
          material={materials.rubber}
        />
      </group>
      <mesh
        geometry={nodes.visual_obj_flipper_left_bottom.geometry}
        material={materials.M_flipper_arm_left}
        position={[-9.887, -5.158, 52.106]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_flipper_right_bottom.geometry}
        material={materials.M_flipper_arm_right}
        position={[5.495, -5.158, 52.106]}
        rotation={[0, Math.PI / 6, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_ball_37.geometry}
        material={materials.lamp_playfield}
        position={[-2.166, -5.129, 54.217]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_obj_gate_5.geometry}
        material={materials.PaletteMaterial001}
        position={[17.242, -1.434, 11.913]}
        rotation={[Math.PI / 2, 0, -1.204]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_ramp_left_sand.geometry}
        material={materials.M_ramps}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_pyramid.geometry}
        material={materials.M_pyramid__Inst}
        position={[-8.531, -5.158, -13.208]}
        rotation={[0, 0.175, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_04_15.geometry}
        material={materials.scarab_flasher}
        position={[-6.711, -0.837, -21.194]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_scarab_flasher_plane_04_14.geometry}
        material={materials.PaletteMaterial001}
        position={[-6.781, -0.519, -21.214]}
        scale={94.51}
      />
      <group
        position={[-22.382, -1.98, -3.51]}
        rotation={[Math.PI / 2, 0, 2.827]}
        scale={94.51}
      >
        <mesh
          geometry={nodes.obj_spinner_LOD0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.obj_spinner_LOD0_1.geometry}
          material={materials.M_spinner}
        />
      </group>
      <mesh
        geometry={nodes.visual_lg_gi_lamps_4.geometry}
        material={materials.lamp_playfield_white}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.GI_bulbs_gfx_LOD0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.GI_bulbs_gfx_LOD0_1.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        geometry={nodes.visual_middle_stuff_overlap.geometry}
        material={materials.M_midlestuff}
        position={[-4.147, -2.451, 42.399]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_slingshot_flash_obj_left.geometry}
        material={materials.M_slingshot_flasher_obj}
        position={[-14.642, -1.733, 35.718]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_slingshot_flash_obj_right.geometry}
        material={materials.M_slingshot_flasher_obj}
        position={[10.22, -1.733, 35.718]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_stared_posts.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.199, -3.953, 38.428]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_screws_slingshots.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.197, -1.887, 38.429]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_right_36.geometry}
        material={materials.lamp_playfield}
        position={[18.401, -5.129, 44.569]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_metals_slingshot.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.155, -4.258, 38.369]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_slingshot_right_shot.geometry}
        material={materials.PaletteMaterial002}
        position={[9.734, -5.972, 38.364]}
        rotation={[0, -Math.PI / 9, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_slingshot_left_shot.geometry}
        material={materials.PaletteMaterial002}
        position={[-14.126, -5.972, 38.364]}
        rotation={[Math.PI / 2, 0, -Math.PI / 9]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_kickback_left_40.geometry}
        material={materials.lamp_playfield}
        position={[-26.819, -5.129, 42.097]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_p.geometry}
        material={materials.lamp_playfield}
        position={[14.431, -5.129, 29.003]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_egypt_t.geometry}
        material={materials.lamp_playfield}
        position={[18.346, -5.129, 28.999]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_metal_post_outlanes_up.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-4.233, -3.196, 46.476]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_sidewalls.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_right_kickback_door.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[16.844, -3.315, 50.409]}
        rotation={[Math.PI, -1.187, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_plunger_back.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-1.377, -5.158, 0.514]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_plunger.geometry}
        material={materials.M_overlap}
        position={[14.504, -10.498, 23.796]}
        scale={94.51}
      />
      <group position={[-1.953, -12.649, 20.335]} scale={94.51}>
        <mesh
          geometry={nodes.holes_nocoll_LOD0.geometry}
          material={materials["M_playfield_cutout.001"]}
        />
        <mesh
          geometry={nodes.holes_nocoll_LOD0_1.geometry}
          material={materials.M_black}
        />
      </group>
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <mesh
          geometry={nodes.waterlvl_LOD0.geometry}
          material={materials.gold}
        />
        <mesh
          geometry={nodes.waterlvl_LOD0_1.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          geometry={nodes.waterlvl_LOD0_2.geometry}
          material={materials.waterlvl}
        />
      </group>
      <mesh
        geometry={nodes.visual_ball_rollover.geometry}
        material={materials.PaletteMaterial002}
        position={[25.156, -5.013, 55.654]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bonus_05.geometry}
        material={materials.PaletteMaterial002}
        position={[18.468, -5.006, 33.396]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bonus_01.geometry}
        material={materials.PaletteMaterial002}
        position={[-26.844, -5.006, 33.396]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bonus_02.geometry}
        material={materials.PaletteMaterial002}
        position={[-22.902, -5.006, 33.396]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bonus_03.geometry}
        material={materials.PaletteMaterial002}
        position={[-18.961, -5.006, 33.396]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_bonus_04.geometry}
        material={materials.PaletteMaterial002}
        position={[14.526, -5.006, 33.396]}
        scale={94.51}
      />
      <group position={[20.46, -3.976, 32.521]} scale={94.51}>
        <mesh
          geometry={nodes.posts_outlane_LOD0.geometry}
          material={materials.rubber}
        />
        <mesh
          geometry={nodes.posts_outlane_LOD0_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <mesh
        geometry={nodes.visual_playfield.geometry}
        material={materials.playfield}
        position={[-1.212, -5.158, 15.409]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_left_orbit_1.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-25.612, -7.838, -13.34]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_pf_door_right.geometry}
        material={materials.playfield}
        position={[0.636, -5.252, 25.546]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_pf_door_left.geometry}
        material={materials.playfield}
        position={[-5.034, -5.252, 25.546]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_under_pf.geometry}
        material={materials.M_underplayfield}
        position={[-2.199, -7.379, 25.546]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_anu_card_01_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[14.648, -8.517, 14.462]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_anu_card_02_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[14.266, -8.517, 15.213]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_anu_card_03_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[13.891, -8.517, 15.949]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_anu_card_04_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[13.523, -8.517, 16.671]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_anu_card_05_gfx.geometry}
        material={materials.M_army_of_anubis}
        position={[13.162, -8.517, 17.379]}
        rotation={[-Math.PI, 0.051, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_lg_army_of_anubis_02.geometry}
        material={materials.M_anubis_head_eyes}
        position={[13.512, -5.158, -0.808]}
        rotation={[0, 1.286, -Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_plunger.geometry}
        material={materials.PaletteMaterial002}
        position={[25.156, -3.882, 69.077]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_right_orbit.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[23.946, -7.838, -10.331]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_center03.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[4.081, -6.573, -17.802]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_center01.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[2.102, -6.573, -16.91]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.visual_diverter_center02_21.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[3.664, -6.986, -17.294]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_habit_left.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_habit_mini_pf.geometry}
        material={materials.PaletteMaterial002}
        position={[18.478, 6.226, -11.97]}
        scale={94.51}
      />
      {/* <mesh */}
      {/*   geometry={nodes.coll_habit_right.geometry} */}
      {/*   material={materials.PaletteMaterial002} */}
      {/*   position={[14.698, -0.241, 17.207]} */}
      {/*   scale={94.51} */}
      {/* /> */}
      <mesh
        geometry={nodes.coll_ramp_back.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.145, 2.154, -30.962]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_top.geometry}
        material={materials.PaletteMaterial002}
        position={[21.825, 9.603, -26.765]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_standard_collision.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.259, -2.322, 15.444]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_habit_vuk.geometry}
        material={materials.PaletteMaterial002}
        position={[25.162, -2.181, -38.778]}
        rotation={[0, 0.048, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_sphinx_bottom.geometry}
        material={materials.PaletteMaterial002}
        position={[-14.413, 6.799, -35.257]}
        rotation={[0, 0.419, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_mummy.geometry}
        material={materials.PaletteMaterial002}
        position={[-7.138, -6.587, 3.92]}
        rotation={[-1.745, 1.396, -3.142]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_scarabeus.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.668, -5.005, 38.783]}
        rotation={[-Math.PI, 1.269, Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_locker.geometry}
        material={materials.PaletteMaterial002}
        position={[13.241, 11.226, -35.066]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_ramp_back001.geometry}
        material={nodes.coll_ramp_back001.material}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_flipper_mini_left.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.148, 6.82, -22.066]}
        rotation={[0, -0.855, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_flipper_mini_left001.geometry}
        material={materials.PaletteMaterial002}
        position={[11.295, 6.82, -22.523]}
        rotation={[0, -1.012, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_flipper_mini_right.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.759, 6.82, -22.973]}
        rotation={[0, 0.96, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_flipper_mini_right001.geometry}
        material={materials.PaletteMaterial002}
        position={[23.193, 6.82, -19.859]}
        rotation={[0, 0.367, Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bumper01.geometry}
        material={materials.PaletteMaterial002}
        position={[0.627, 3.664, -31.836]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bumper02.geometry}
        material={materials.PaletteMaterial002}
        position={[11.095, 3.664, -29.611]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bumper03.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.277, 3.664, -22.878]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bumper04.geometry}
        material={materials.PaletteMaterial002}
        position={[9.191, 3.664, -20.653]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_locker_launch.geometry}
        material={materials.PaletteMaterial002}
        position={[13.26, 10.78, -34.742]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_mpf_spindisk_wall.geometry}
        material={materials.PaletteMaterial002}
        position={[-10.872, 7.741, -31.265]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_blunt_rubber.geometry}
        material={materials.PaletteMaterial002}
        position={[1.621, 2.144, -9.01]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_droptarget_mpf_01.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.016, 6.277, -28.049]}
        rotation={[0, Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_droptarget_mpf_02.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.295, 6.277, -28.532]}
        rotation={[0, Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_droptarget_mpf_03.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.574, 6.277, -29.016]}
        rotation={[0, Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_droptarget_mpf_04.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.853, 6.277, -29.499]}
        rotation={[0, Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_droptarget_mpf_05.geometry}
        material={materials.PaletteMaterial002}
        position={[-18.132, 6.277, -29.983]}
        rotation={[0, Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_mpf_metal_wires.geometry}
        material={materials.PaletteMaterial002}
        position={[3.243, 7.741, -28.466]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_scoops01_6.geometry}
        material={materials.PaletteMaterial002}
        position={[-3.855, 2.609, -46.733]}
        rotation={[0, 0.517, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_ramp_right.geometry}
        material={materials.PaletteMaterial002}
        position={[-6.869, -5.158, -16.164]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_rubber.geometry}
        material={materials.PaletteMaterial002}
        position={[-4.151, 0.11, -2.985]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_super_rubber.geometry}
        material={materials.PaletteMaterial002}
        position={[-4.166, 2.154, 1.999]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_nile.geometry}
        material={materials.PaletteMaterial002}
        position={[4.909, 2.719, -26.245]}
        rotation={[0, -0.209, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_mpf_spinner.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-5.139, 6.799, -34.48]}
        rotation={[0, -1.309, Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_miniplayfield.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.49, 6.799, -32.435]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bridge_part_01.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.049, 6.744, -28.022]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bridge_part_02.geometry}
        material={materials.PaletteMaterial002}
        position={[2.087, 6.744, -28.222]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bridge_part_03.geometry}
        material={materials.PaletteMaterial002}
        position={[4.223, 6.744, -28.12]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_bridge_part_04.geometry}
        material={materials.PaletteMaterial002}
        position={[6.359, 6.744, -27.664]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_gate_mpf_left.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.513, 10.464, -41.991]}
        rotation={[Math.PI / 2, 0, 1.466]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_gate_mpf_right_2.geometry}
        material={materials.PaletteMaterial002}
        position={[11.917, 10.464, -41.834]}
        rotation={[Math.PI / 2, 0, -1.431]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_target.geometry}
        material={materials.PaletteMaterial002}
        position={[18.875, 8.136, -29.962]}
        rotation={[Math.PI / 2, 0, 0.244]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_target001.geometry}
        material={materials.PaletteMaterial002}
        position={[23.212, 8.136, -25.745]}
        rotation={[Math.PI / 2, 0, 1.1]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_spindisk_mpf.geometry}
        material={materials.PaletteMaterial002}
        position={[-5.139, 6.799, -34.48]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_to_vuk.geometry}
        material={materials.PaletteMaterial002}
        position={[25.162, -2.322, -23.272]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_flipper_left_bottom.geometry}
        material={materials.PaletteMaterial002}
        position={[-9.887, -5.158, 52.106]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_flipper_right_bottom.geometry}
        material={materials.PaletteMaterial002}
        position={[5.495, -5.158, 52.106]}
        rotation={[0, Math.PI / 6, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_gate.geometry}
        material={materials.PaletteMaterial002}
        position={[17.242, -1.434, 11.913]}
        rotation={[Math.PI / 2, 0, -1.204]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_safe_pyramid.geometry}
        material={materials.PaletteMaterial002}
        position={[-9.018, 0.829, -15.553]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_pyramid.geometry}
        material={materials.PaletteMaterial002}
        position={[-8.531, -5.158, -13.208]}
        rotation={[0, 0.175, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_pyramid_temporary.geometry}
        material={materials.PaletteMaterial002}
        position={[-8.529, -3.239, -13.205]}
        rotation={[0, 0.175, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_pyramid_wall_03.geometry}
        material={materials.PaletteMaterial002}
        position={[-9.38, -5.158, -18.023]}
        rotation={[0, 0.175, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_pyramid_door.geometry}
        material={materials.PaletteMaterial002}
        position={[-8.531, -5.158, -13.208]}
        rotation={[0, 0.175, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_spinner_10.geometry}
        material={materials.PaletteMaterial002}
        position={[-22.382, -1.98, -3.51]}
        rotation={[Math.PI / 2, 0, 2.827]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_metal.geometry}
        material={materials.PaletteMaterial002}
        position={[0.609, -4.213, 47.048]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_scoops.geometry}
        material={materials.PaletteMaterial002}
        position={[-10.952, -9.22, -5.479]}
        rotation={[0, 0.579, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_ramp_left.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.378, -3.267, -12.551]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anubis_head_hole.geometry}
        material={materials.PaletteMaterial002}
        position={[13.093, -5.133, 0.296]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_locker_door_11.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.212, -4.102, 10.211]}
        rotation={[0, -0.134, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_fr_slingshot_flasher_left.geometry}
        material={materials.lamp_playfield_white}
        position={[-14.642, -1.733, 35.718]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_fr_slingshot_flasher_right.geometry}
        material={materials.lamp_playfield_white}
        position={[10.22, -1.733, 35.718]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_ramp_metal.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.158, -3.74, 42.719]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_sidewalls.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.11, -3.834, 16.521]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_left_kickback_door.geometry}
        material={materials["metal_sidewalls.001"]}
        position={[-26.822, -3.834, 46.745]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_plunger_back.geometry}
        material={materials.PaletteMaterial002}
        position={[25.14, -3.834, -11.395]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_plunger.geometry}
        material={materials.PaletteMaterial002}
        position={[14.504, -10.498, 23.796]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anubis_mouth.geometry}
        material={materials.PaletteMaterial002}
        position={[12.408, -3.701, 2.31]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_posts_outlane.geometry}
        material={materials.PaletteMaterial002}
        position={[-4.118, -3.834, 32.521]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_playfield_collision.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.212, -5.158, 15.409]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_left_hole.geometry}
        material={materials.PaletteMaterial002}
        position={[-24.811, -10.998, 11.52]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_left_orbit_0.geometry}
        material={materials.PaletteMaterial002}
        position={[-25.612, -7.838, -13.34]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_under_pf.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.199, -7.379, 25.546]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anu_card_01.geometry}
        material={materials.PaletteMaterial002}
        position={[14.648, -8.517, 14.462]}
        rotation={[-Math.PI, 0.054, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anu_card_02.geometry}
        material={materials.PaletteMaterial002}
        position={[14.266, -8.517, 15.213]}
        rotation={[-Math.PI, 0.054, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anu_card_03.geometry}
        material={materials.PaletteMaterial002}
        position={[13.891, -8.517, 15.949]}
        rotation={[-Math.PI, 0.068, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anu_card_04.geometry}
        material={materials.PaletteMaterial002}
        position={[13.523, -8.517, 16.671]}
        rotation={[-Math.PI, 0.061, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_anu_card_05.geometry}
        material={materials.PaletteMaterial002}
        position={[13.162, -8.517, 17.379]}
        rotation={[-Math.PI, 0.054, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_right_orbit.geometry}
        material={materials.PaletteMaterial002}
        position={[23.322, -6.515, -10.353]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_center02_20.geometry}
        material={materials.PaletteMaterial002}
        position={[3.664, -6.986, -17.294]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_center03.geometry}
        material={materials.PaletteMaterial002}
        position={[4.081, -6.573, -17.802]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_diverter_center01.geometry}
        material={materials.PaletteMaterial002}
        position={[2.102, -6.573, -16.91]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_right_sling_collision_bottom.geometry}
        material={materials.PaletteMaterial002}
        position={[7.044, -3.74, 43.312]}
        rotation={[-Math.PI / 2, 0, 1.222]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_left_sling_collision_bottom.geometry}
        material={materials.PaletteMaterial002}
        position={[-11.438, -3.834, 43.312]}
        rotation={[Math.PI / 2, 0, -1.92]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_left_sling_collision_top.geometry}
        material={materials.PaletteMaterial002}
        position={[-15.236, -3.834, 32.859]}
        rotation={[-Math.PI / 2, 0, -1.222]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.coll_right_sling_collision_top.geometry}
        material={materials.PaletteMaterial002}
        position={[10.841, -3.74, 32.859]}
        rotation={[Math.PI / 2, 0, 1.92]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_mpf_presence_0.geometry}
        material={materials.PaletteMaterial002}
        position={[4.569, 8.434, -29.177]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_mini_left001_arm.geometry}
        material={materials.PaletteMaterial002}
        position={[11.295, 6.82, -22.523]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_mini_left_arm.geometry}
        material={materials.PaletteMaterial002}
        position={[-17.148, 6.82, -22.066]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_mini_right001_arm.geometry}
        material={materials.PaletteMaterial002}
        position={[23.193, 6.82, -19.859]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_mini_right_arm.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.759, 6.82, -22.973]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_nile.geometry}
        material={materials.PaletteMaterial002}
        position={[5.204, 3.637, -26.715]}
        rotation={[0, -0.209, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_bridge_left.geometry}
        material={materials.PaletteMaterial002}
        position={[-1.789, 8.487, -27.693]}
        rotation={[0, 0.055, -Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_bridge_right.geometry}
        material={materials.PaletteMaterial002}
        position={[10.301, 8.487, -26.414]}
        rotation={[0, 0.053, Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_bridge.geometry}
        material={materials.PaletteMaterial002}
        position={[4.403, 7.338, -26.813]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_left_bottom_arm.geometry}
        material={materials.PaletteMaterial002}
        position={[-9.877, -5.158, 52.089]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_right_bottom_arm.geometry}
        material={materials.PaletteMaterial002}
        position={[5.486, -5.158, 52.089]}
        rotation={[0, Math.PI / 6, -Math.PI]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.stick_barrier.geometry}
        material={materials.PaletteMaterial002}
        position={[-3.689, -3.882, 46.734]}
        rotation={[0, -1.571, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.TrialHoleDrainSensor.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.133, -3.882, 63.678]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.launched.geometry}
        material={materials.PaletteMaterial002}
        position={[22.551, -3.882, 25.498]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.sensor_sinkhole_left.geometry}
        material={materials.PaletteMaterial002}
        position={[-25.383, -14.228, 10.656]}
        rotation={[0, 0.593, Math.PI / 2]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.ballHouse.geometry}
        material={materials.PaletteMaterial002}
        position={[-3.258, -18.13, 61.566]}
        rotation={[0, -1.571, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.ballhouse_box.geometry}
        material={materials.PaletteMaterial002}
        position={[-2.964, -18.253, 61.712]}
        rotation={[0, -1.571, 0]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.path_scarabs_center_hole.geometry}
        material={materials.PaletteMaterial002}
        position={[0.303, -5.12, 16.295]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.path_scarabs_left_hole.geometry}
        material={materials.PaletteMaterial002}
        position={[-13.603, -5.12, 33.459]}
        scale={94.51}
      />
      <mesh
        geometry={nodes.path_scarabs_right_hole.geometry}
        material={materials.PaletteMaterial002}
        position={[6.036, -5.12, 27.931]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_anubis.geometry}
        material={materials.M_anubis_head}
        skeleton={nodes.visual_anubis.skeleton}
        position={[13.512, -5.158, -0.808]}
        rotation={[0, -0.373, 0]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_ornate_torch_04_20.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_ornate_torch_04_20.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.coll_locker_door_2001.geometry}
        material={nodes.coll_locker_door_2001.material}
        skeleton={nodes.coll_locker_door_2001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_locker_door_2.geometry}
        material={materials.M_locker}
        skeleton={nodes.visual_locker_door_2.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_sarcophagus01_door_3001.geometry}
        material={materials.M_sarcophagus}
        skeleton={nodes.visual_sarcophagus01_door_3001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_anubis_under_pf_11001.geometry}
        material={materials.M_anubis_head}
        skeleton={nodes.visual_anubis_under_pf_11001.skeleton}
        position={[-12.018, -9.447, 19.403]}
        rotation={[0, 1.571, 0]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_scarabeus.geometry}
        material={materials.M_scarabeus}
        skeleton={nodes.visual_scarabeus.skeleton}
        position={[-2.787, -3.823, 38.518]}
        rotation={[0, 0.036, 0]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_anubis_under_pf2001.geometry}
        material={materials.M_anubis_head}
        skeleton={nodes.visual_anubis_under_pf2001.skeleton}
        position={[7.546, -9.807, 31.689]}
        rotation={[-1.568, -1.568, -1.568]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_torch_left_24001.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_torch_left_24001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_torch_right_28001.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_torch_right_28001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_ornate_torch_01_14001.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_ornate_torch_01_14001.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_ornate_torch_03_17.geometry}
        material={materials.M_Torches}
        skeleton={nodes.visual_ornate_torch_03_17.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead1001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead1001.skeleton}
        position={[-0.876, 3.675, -33.212]}
        rotation={[-Math.PI, -0.806, -Math.PI]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead2_19001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead2_19001.skeleton}
        position={[13.093, 3.675, -29.937]}
        rotation={[-Math.PI, 1.394, -Math.PI]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead3001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead3001.skeleton}
        position={[-3.224, 3.675, -22.252]}
        rotation={[0, -1.312, 0]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_crochead4_18001.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crochead4_18001.skeleton}
        position={[10.787, 3.675, -19.151]}
        rotation={[0, 0.806, 0]}
        scale={78.86}
      />
      <skinnedMesh
        geometry={nodes.visual_waterlvl_bubble_2001.geometry}
        material={materials.water_level_bubble}
        skeleton={nodes.visual_waterlvl_bubble_2001.skeleton}
        position={[-1.78, -5.318, 10.211]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_crocodile_plunger.geometry}
        material={materials.M_crocodile_plunger}
        skeleton={nodes.visual_crocodile_plunger.skeleton}
        position={[-1.212, -5.158, 10.211]}
        scale={94.51}
      />
      <group position={[-1.212, -5.158, 10.211]} scale={94.51}>
        <skinnedMesh
          geometry={nodes.mummy_LOD0.geometry}
          material={materials.M_mummy}
          skeleton={nodes.mummy_LOD0.skeleton}
        />
        <skinnedMesh
          geometry={nodes.mummy_LOD0_1.geometry}
          material={materials.M_mummy_eye}
          skeleton={nodes.mummy_LOD0_1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.mummy_LOD0_2.geometry}
          material={materials.M_mummy_jewel}
          skeleton={nodes.mummy_LOD0_2.skeleton}
        />
      </group>
      <skinnedMesh
        geometry={nodes.visual_slingshot_left_10001.geometry}
        material={materials.rubber}
        skeleton={nodes.visual_slingshot_left_10001.skeleton}
        position={[-13.605, -3.882, 38.178]}
        scale={94.51}
      />
      <skinnedMesh
        geometry={nodes.visual_slingshot_right_7001.geometry}
        material={materials.rubber}
        skeleton={nodes.visual_slingshot_right_7001.skeleton}
        position={[9.735, -3.882, 38.364]}
        scale={94.51}
      />
    </group>
  );
}

useGLTF.preload("/models/PinballMVP2-transformed.glb");
