/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/PinballMVP_Maker.glb -T -t -j -o src/components/models/PinballMVP_Maker.tsx 
Files: public/models/PinballMVP_Maker.glb [77.88KB] > /home/steph/hetic/Pinball_three.js/frontend/src/components/models/PinballMVP_Maker-transformed.glb [19.8KB] (75%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    coll_maker_playfield_collision: THREE.Mesh
    coll_maker_gate: THREE.Mesh
    coll_maker_standard_collision_sidewalls: THREE.Mesh
    coll_maker_flipper_left_bottom: THREE.Mesh
    coll_maker_flipper_right_bottom: THREE.Mesh
    coll_maker_super_rubber: THREE.Mesh
    coll_maker_metal: THREE.Mesh
    coll_maker_sidewalls: THREE.Mesh
    coll_maker_slingshot_left: THREE.Mesh
    coll_maker_slingshot_right: THREE.Mesh
    coll_maker_glass_panel: THREE.Mesh
    coll_maker_guidance_right: THREE.Mesh
    coll_maker_guidance_left: THREE.Mesh
  }
  materials: {
    collision: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function PinballMVPMaker(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/PinballMVP_Maker-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.coll_maker_playfield_collision.geometry} material={materials.collision} position={[-0.609, -2.903, 7.762]} />
      <mesh geometry={nodes.coll_maker_gate.geometry} material={nodes.coll_maker_gate.material} position={[8.733, -1.272, 5.992]} />
      <mesh geometry={nodes.coll_maker_standard_collision_sidewalls.geometry} material={nodes.coll_maker_standard_collision_sidewalls.material} position={[-0.633, -10.856, 7.78]} />
      <mesh geometry={nodes.coll_maker_flipper_left_bottom.geometry} material={nodes.coll_maker_flipper_left_bottom.material} position={[-5.001, -2.901, 26.34]} />
      <mesh geometry={nodes.coll_maker_flipper_right_bottom.geometry} material={nodes.coll_maker_flipper_right_bottom.material} position={[2.787, -2.901, 26.34]} />
      <mesh geometry={nodes.coll_maker_super_rubber.geometry} material={nodes.coll_maker_super_rubber.material} position={[-2.105, 0.799, 0.974]} />
      <mesh geometry={nodes.coll_maker_metal.geometry} material={nodes.coll_maker_metal.material} position={[0.313, -2.424, 23.779]} />
      <mesh geometry={nodes.coll_maker_sidewalls.geometry} material={nodes.coll_maker_sidewalls.material} position={[-0.557, -2.126, 8.325]} />
      <mesh geometry={nodes.coll_maker_slingshot_left.geometry} material={nodes.coll_maker_slingshot_left.material} position={[-0.633, -1.467, 7.78]} />
      <mesh geometry={nodes.coll_maker_slingshot_right.geometry} material={nodes.coll_maker_slingshot_right.material} position={[-2.105, 0.799, 0.974]} />
      {/* <mesh geometry={nodes.coll_maker_glass_panel.geometry} material={materials.collision} position={[-0.609, -1.388, 7.762]} /> */}
      <mesh geometry={nodes.coll_maker_guidance_right.geometry} material={nodes.coll_maker_guidance_right.material} position={[-1.088, -2.185, 21.588]} />
      <mesh geometry={nodes.coll_maker_guidance_left.geometry} material={nodes.coll_maker_guidance_left.material} position={[-0.633, -1.467, 7.78]} />
    </group>
  )
}

useGLTF.preload('/models/PinballMVP_Maker-transformed.glb')
