server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Redirige toutes les requêtes vers index.html (pour React Router)
        try_files $uri $uri/ /index.html;
    }

    # Cache pour les fichiers statiques (assets 3D, sons, images)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|glb|gltf|mp3|wav)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
