[app]
id          = "t1-flipper"
name        = "t1-flipper"
authors     = ["Adrien ALLARD"] 
description = "Projet de WEB3"

[deploy]
strategy = "branch"                 
ref      = "main"                   

[screens]
playfield = { service = "frontend", port = 80, path = "/playfield?mode=arcade" }
backglass = { service = "frontend", port = 80, path = "/backglass" }
dmd       = { service = "frontend", port = 80, path = "/dmd" }

[compose]
file          = "deploy/docker-compose.yml"
ready_timeout = 30

[esp32.esp32]
firmware = "firmware/build/firmware.bin"
flash_addr = "0x0"
chip     = "esp32"