name: Déploiement VPS Production

# Se lance quand le workflow "Tests & Coverage" se termine avec succès sur main
on:
  workflow_run:
    workflows: ["Tests & Coverage"]
    types:
      - completed
    branches:
      - main


jobs:
  deploy:
    # N'exécute le déploiement que si les tests ont réussi
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: VPS_ENV

    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Synchronisation des fichiers vers le VPS (rsync)
        uses: burnett01/rsync-deployments@7.0.1 # ne modif que les fichiers modifier dans le dépot, évite un "downtime"
        with:
          switches: -avz --delete --exclude='.env' --exclude='.git' --exclude='node_modules'
          path: ./
          remote_path: ~/flipper-project/
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USERNAME }}
          remote_key: ${{ secrets.VPS_SSH_KEY }}
      - name: Lancement de l'environnement de Prod sur le VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Création du dossier s'il n'existe pas (sécurité au premier déploiement)
            cd ~/flipper-project
          
            # Injection des secrets
            echo "MQTT_USERNAME=${{ secrets.MQTT_USERNAME }}" > .env
            echo "MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }}" >> .env
            
            # Déploiement
            sudo docker compose -f compose.prod.yml up -d --build
            
            # Nettoyage des anciennes images inutilisées (libère de la place)
            sudo docker image prune -f
            
            # Vérification de santé
            echo "Vérification du statut..."
            sleep 10
            sudo docker compose -f compose.prod.yml ps